# SQL CARTO QUERY FUNCTION
# written for PUI2016_Python2
#### and make it python 2 and 3 compatible by Hao Xi.

##### This notebook is set up to link as a default to the fb55 account.  To turn in the homework use the same account you used in the lab (hvt201)  and query the database that you were querying in class (citibike_feb_2015, named as citibike)

In [6]:
SQL_SOURCE = 'https://hx517.carto.com/api/v2/sql?q='

try:
    from urllib.request import urlopen
except ImportError:
    from urllib2 import urlopen
try:
    from urllib.error import HTTPError
except ImportError:
    from urllib2 import HTTPError
try:
    from urllib.parse import urlencode
except ImportError:
    from urllib import urlencode
import io
import ast
import pandas as pd
# try to make it python 2 and 3 compatible.

def queryCartoDB(query, format='CSV', source=SQL_SOURCE):
    '''queries carto datasets from a given carto account
    Arguments: 
    query - string: a valid sql query string
    format - outlut format  OPTIONAL (default CSV)
    source - a valid sql api endpoint OPTIONAL (default carto fb55 account)
    Returns:
    the return of the sql query AS A STRING
    NOTES:
    designed for the carto API, tested only with CSV return format'''
    
    data = urllib.urlencode({'format': format, 'q': query})
    try:
        response = urllib2.urlopen(source, data)
    except urllib2.HTTPError, e:
        raise ValueError('\n'.join(ast.literal_eval(e.readline())['error']))
    except Exception:
        raise
    return response.read()

In [7]:
test = '''
SELECT *
FROM citibike
'''

In [8]:
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

,cartodb_id,the_geom,the_geom_webmercator,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,5960,NaN,NaN,351,2015-02-01 20:36:00+00,2015-02-01 20:42:00+00,435,W 21 St & 6 Ave,40.741740,-73.994156,462,W 22 St & 10 Ave,40.746920,-74.004519,19217,Subscriber,1965.0,1
1,9806,NaN,NaN,643,2015-02-03 14:39:00+00,2015-02-03 14:50:00+00,167,E 39 St & 3 Ave,40.748901,-73.976049,488,W 39 St & 9 Ave,40.756458,-73.993722,17575,Subscriber,1971.0,1
2,13113,NaN,NaN,1379,2015-02-04 07:07:00+00,2015-02-04 07:30:00+00,332,Cherry St,40.712199,-73.979481,440,E 45 St & 3 Ave,40.752554,-73.972826,20313,Subscriber,1973.0,1
3,1,NaN,NaN,801,2015-02-01 00:00:00+00,2015-02-01 00:14:00+00,521,8 Ave & W 31 St,40.750450,-73.994811,423,W 54 St & 9 Ave,40.765849,-73.986905,17131,Subscriber,1978.0,2
4,2,NaN,NaN,379,2015-02-01 00:00:00+00,2015-02-01 00:07:00+00,497,E 17 St & Broadway,40.737050,-73.990093,504,1 Ave & E 15 St,40.732219,-73.981656,21289,Subscriber,1993.0,1
5,3,NaN,NaN,2474,2015-02-01 00:01:00+00,2015-02-01 00:42:00+00,281,Grand Army Plaza & Central Park S,40.764397,-73.973715,127,Barrow St & Hudson St,40.731724,-74.006744,18903,Subscriber,1969.0,2
6,4,NaN,NaN,818,2015-02-01 00:01:00+00,2015-02-01 00:15:00+00,2004,6 Ave & Broome St,40.724399,-74.004704,505,6 Ave & W 33 St,40.749013,-73.988484,21044,Subscriber,1985.0,2
7,5,NaN,NaN,544,2015-02-01 00:01:00+00,2015-02-01 00:10:00+00,323,Lawrence St & Willoughby St,40.692362,-73.986317,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,19868,Subscriber,1957.0,1
8,6,NaN,NaN,717,2015-02-01 00:02:00+00,2015-02-01 00:14:00+00,373,Willoughby Ave & Walworth St,40.693317,-73.953820,2002,Wythe Ave & Metropolitan Ave,40.716887,-73.963198,15854,Subscriber,1979.0,1
9,7,NaN,NaN,1306,2015-02-01 00:04:00+00,2015-02-01 00:26:00+00,352,W 56 St & 6 Ave,40.763406,-73.977225,504,1 Ave & E 15 St,40.732219,-73.981656,15173,Subscriber,1983.0,1
10,8,NaN,NaN,913,2015-02-01 00:04:00+00,2015-02-01 00:19:00+00,439,E 4 St & 2 Ave,40.726281,-73.989780,116,W 17 St & 8 Ave,40.741776,-74.001497,17862,Subscriber,1955.0,1
11,9,NaN,NaN,759,2015-02-01 00:04:00+00,2015-02-01 00:17:00+00,335,Washington Pl & Broadway,40.729039,-73.994046,2012,E 27 St & 1 Ave,40.739445,-73.976806,21183,Subscriber,1985.0,2
12,10,NaN,NaN,585,2015-02-01 00:05:00+00,2015-02-01 00:15:00+00,284,Greenwich Ave & 8 Ave,40.739017,-74.002638,444,Broadway & W 24 St,40.742354,-73.989151,14843,Subscriber,1982.0,1
13,11,NaN,NaN,581,2015-02-01 00:05:00+00,2015-02-01 00:15:00+00,284,Greenwich Ave & 8 Ave,40.739017,-74.002638,444,Broadway & W 24 St,40.742354,-73.989151,16936,Subscriber,1988.0,2
14,12,NaN,NaN,204,2015-02-01 00:05:00+00,2015-02-01 00:08:00+00,498,Broadway & W 32 St,40.748549,-73.988084,472,E 32 St & Park Ave,40.745712,-73.981948,21507,Subscriber,1991.0,2
15,13,NaN,NaN,1169,2015-02-01 00:07:00+00,2015-02-01 00:27:00+00,368,Carmine St & 6 Ave,40.730386,-74.002150,307,Canal St & Rutgers St,40.714275,-73.989900,17456,Subscriber,1982.0,2
16,14,NaN,NaN,419,2015-02-01 00:07:00+00,2015-02-01 00:14:00+00,326,E 11 St & 1 Ave,40.729538,-73.984267,2012,E 27 St & 1 Ave,40.739445,-73.976806,14679,Subscriber,1990.0,2
17,15,NaN,NaN,527,2015-02-01 00:09:00+00,2015-02-01 00:17:00+00,285,Broadway & E 14 St,40.734546,-73.990741,212,W 16 St & The High Line,40.743349,-74.006818,18978,Subscriber,1977.0,1
18,16,NaN,NaN,1013,2015-02-01 00:10:00+00,2015-02-01 00:27:00+00,368,Carmine St & 6 Ave,40.730386,-74.002150,488,W 39 St & 9 Ave,40.756458,-73.993722,16496,Subscriber,1968.0,1
19,17,NaN,NaN,587,2015-02-01 00:13:00+00,2015-02-01 00:23:00+00,394,E 9 St & Avenue C,40.725213,-73.977688,331,Pike St & Monroe St,40.711731,-73.991930,17107,Subscriber,1990.0,1
20,18,NaN,NaN,525,2015-02-01 00:13:00+00,2015-02-01 00:22:00+00,326,E 11 St & 1 Ave,40.729538,-73.984267,507,E 25 St & 2 Ave,40.739126,-73.979738,16984,Subscriber,1987.0,1
21,19,NaN,NaN,670,2015-02-01 00:14:00+00,2015-02-01 00:26:00+00,493,W 45 St & 6 Ave,40.756800,-73.982912,305,E 58 St & 3 Ave,40.760958,-73.967245,15997,Subscriber,1980.0,1
22,20,NaN,NaN,711,2015-02-01 00:15:00+00,2015-02-01 00:27:00+00,445,E 10 St & Avenue A,40.727408,-73.981420,223,W 13 St & 7 Ave,40.737815,-73.999947,21516,Subscriber,1960.0,1
23,21,NaN,NaN,1559,2015-02-01 00:16:00+00,2015-02-01 00:42:00+00,428,E 3 St & 1 Ave,40.724677,-73.987834,457,Broadway & W 58 St,40.766953,-73.981693,15815,Subscriber,1986.0,1
24,22,NaN,NaN,683,2015-02-01 00:16:00+00,2015-02-01 00:27:00+00,228,E 48 St & 3 Ave,40.754601,-73.971879,477,W 41 St & 8 Ave,40.756405,-73.990026,18727,Subscriber,1987.0,1
25,23,NaN,NaN,522,2015-02-01 00:16:00+00,2015-02-01 00:24:00+00,513,W 56 St & 10 Ave,40.768254,-73.988639,488,W 39 St & 9 Ave,40.756458,-73.993722,14982,Subscriber,1969.0,1
26,24,NaN,NaN,389,2015-02-01 00:16:00+00,2015-02-01 00:23:00+00,507,E 25 St & 2 Ave,40.739126,-73.979738,518,E 39 St & 2 Ave,40.747804,-73.973442,16391,Subscriber,1957.0,1
27,25,NaN,NaN,276,2015-02-01 00:16:00+00,2015-02-01 00:21:00+00,439,E 4 St & 2 Ave,40.726281,-73.989780,473,Rivington St & Chrystie St,40.721101,-73.991925,15947,Subscriber,1981.0,1
28,26,NaN,NaN,907,2015-02-01 00:17:00+00,2015-02-01 00:32:00+00,128,MacDougal St & Prince St,40.727103,-74.002971,531,Forsyth St & Broome St,40.718939,-73.992663,16917,Subscriber,1993.0,1
29,27,NaN,NaN,946,2015-02-01 00:18:00+00,2015-02-01 00:33:00+00,490,8 Ave & W 33 St,40.751551,-73.993934,528,2 Ave & E 31 St,40.742909,-73.977061,15924,Subscriber,1975.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46170,46171,NaN,NaN,812,2015-02-07 23:51:00+00,2015-02-08 00:05:00+00,335,Washington Pl & Broadway,40.729039,-73.994046,435,W 21 St & 6 Ave,40.741740,-73.994156,15733,Subscriber,1988.0,1
46171,46172,NaN,NaN,647,2015-02-07 23:51:00+00,2015-02-08 00:02:00+00,361,Allen St & Hester St,40.716059,-73.991908,504,1 Ave & E 15 St,40.732219,-73.981656,16931,Subscriber,1995.0,1
46172,46173,NaN,NaN,563,2015-02-07 23:51:00+00,2015-02-08 00:00:00+00,152,Warren St & Church St,40.714740,-74.009106,401,Allen St & Rivington St,40.720196,-73.989978,17202,Subscriber,1987.0,1
46173,46174,NaN,NaN,470,2015-02-07 23:51:00+00,2015-02-07 23:59:00+00,483,E 12 St & 3 Ave,40.732233,-73.988900,439,E 4 St & 2 Ave,40.726281,-73.989780,20314,Subscriber,1989.0,2
46174,46175,NaN,NaN,299,2015-02-07 23:51:00+00,2015-02-07 23:56:00+00,467,Dean St & 4 Ave,40.683125,-73.978951,395,Bond St & Schermerhorn St,40.688070,-73.984106,21531,Subscriber,1989.0,1
46175,46176,NaN,NaN,629,2015-02-07 23:52:00+00,2015-02-08 00:02:00+00,361,Allen St & Hester St,40.716059,-73.991908,504,1 Ave & E 15 St,40.732219,-73.981656,21491,Subscriber,1968.0,1
46176,46177,NaN,NaN,499,2015-02-07 23:52:00+00,2015-02-08 00:00:00+00,402,Broadway & E 22 St,40.740343,-73.989551,380,W 4 St & 7 Ave S,40.734011,-74.002939,15367,Subscriber,1990.0,1
46177,46178,NaN,NaN,474,2015-02-07 23:52:00+00,2015-02-08 00:00:00+00,369,Washington Pl & 6 Ave,40.732241,-74.000264,368,Carmine St & 6 Ave,40.730386,-74.002150,18978,Subscriber,1973.0,2
46178,46179,NaN,NaN,345,2015-02-07 23:52:00+00,2015-02-07 23:58:00+00,476,E 31 St & 3 Ave,40.743943,-73.979661,504,1 Ave & E 15 St,40.732219,-73.981656,19507,Subscriber,1980.0,1
46179,46180,NaN,NaN,829,2015-02-07 23:53:00+00,2015-02-08 00:07:00+00,499,Broadway & W 60 St,40.769155,-73.981918,160,E 37 St & Lexington Ave,40.748238,-73.978311,16936,Subscriber,1980.0,1
46180,46181,NaN,NaN,776,2015-02-07 23:53:00+00,2015-02-08 00:05:00+00,368,Carmine St & 6 Ave,40.730386,-74.002150,531,Forsyth St & Broome St,40.718939,-73.992663,18689,Subscriber,1982.0,1
46181,46182,NaN,NaN,697,2015-02-07 23:53:00+00,2015-02-08 00:05:00+00,520,W 52 St & 5 Ave,40.759923,-73.976485,478,11 Ave & W 41 St,40.760301,-73.998842,15781,Subscriber,1972.0,1
46182,46183,NaN,NaN,1703,2015-02-07 23:54:00+00,2015-02-08 00:23:00+00,467,Dean St & 4 Ave,40.683125,-73.978951,471,Grand St & Havemeyer St,40.712868,-73.956981,15081,Subscriber,1988.0,1
46183,46184,NaN,NaN,922,2015-02-07 23:54:00+00,2015-02-08 00:10:00+00,479,9 Ave & W 45 St,40.760193,-73.991255,247,Perry St & Bleecker St,40.735354,-74.004831,21672,Subscriber,1983.0,1
46184,46185,NaN,NaN,849,2015-02-07 23:54:00+00,2015-02-08 00:08:00+00,457,Broadway & W 58 St,40.766953,-73.981693,488,W 39 St & 9 Ave,40.756458,-73.993722,16336,Subscriber,1970.0,1
46185,46186,NaN,NaN,826,2015-02-07 23:54:00+00,2015-02-08 00:08:00+00,457,Broadway & W 58 St,40.766953,-73.981693,488,W 39 St & 9 Ave,40.756458,-73.993722,21609,Subscriber,1973.0,1
46186,46187,NaN,NaN,473,2015-02-07 23:54:00+00,2015-02-08 00:02:00+00,328,Watts St & Greenwich St,40.724055,-74.009660,3002,South End Ave & Liberty St,40.711512,-74.015756,19470,Subscriber,1964.0,1
46187,46188,NaN,NaN,332,2015-02-07 23:54:00+00,2015-02-07 23:59:00+00,510,W 51 St & 6 Ave,40.760660,-73.980420,450,W 49 St & 8 Ave,40.762272,-73.987882,18167,Subscriber,1960.0,1
46188,46189,NaN,NaN,456,2015-02-07 23:55:00+00,2015-02-08 00:03:00+00,382,University Pl & E 14 St,40.734927,-73.992005,404,9 Ave & W 14 St,40.740583,-74.005509,15929,Subscriber,1987.0,1
46189,46190,NaN,NaN,327,2015-02-07 23:55:00+00,2015-02-08 00:01:00+00,254,W 11 St & 6 Ave,40.735324,-73.998004,466,W 25 St & 6 Ave,40.743954,-73.991449,17541,Subscriber,1983.0,1
46190,46191,NaN,NaN,306,2015-02-07 23:55:00+00,2015-02-08 00:01:00+00,116,W 17 St & 8 Ave,40.741776,-74.001497,494,W 26 St & 8 Ave,40.747348,-73.997236,14736,Subscriber,1983.0,2
46191,46192,NaN,NaN,1248,2015-02-07 23:56:00+00,2015-02-08 00:17:00+00,495,W 47 St & 10 Ave,40.762699,-73.993012,432,E 7 St & Avenue A,40.726218,-73.983799,16300,Subscriber,1984.0,1
46192,46193,NaN,NaN,1165,2015-02-07 23:56:00+00,2015-02-08 00:15:00+00,152,Warren St & Church St,40.714740,-74.009106,325,E 19 St & 3 Ave,40.736245,-73.984738,16978,Subscriber,1959.0,1
46193,46194,NaN,NaN,993,2015-02-07 23:56:00+00,2015-02-08 00:13:00+00,461,E 20 St & 2 Ave,40.735877,-73.982050,295,Pike St & E Broadway,40.714067,-73.992939,16722,Subscriber,1974.0,1
46194,46195,NaN,NaN,1422,2015-02-07 23:57:00+00,2015-02-08 00:20:00+00,455,1 Ave & E 44 St,40.750020,-73.969053,265,Stanton St & Chrystie St,40.722293,-73.991475,20184,Subscriber,1960.0,2
46195,46196,NaN,NaN,689,2015-02-07 23:57:00+00,2015-02-08 00:08:00+00,470,W 20 St & 8 Ave,40.743453,-74.000040,325,E 19 St & 3 Ave,40.736245,-73.984738,15585,Subscriber,1953.0,1
46196,46197,NaN,NaN,428,2015-02-07 23:57:00+00,2015-02-08 00:04:00+00,474,5 Ave & E 29 St,40.745168,-73.986831,325,E 19 St & 3 Ave,40.736245,-73.984738,16395,Subscriber,1986.0,2
46197,46198,NaN,NaN,392,2015-02-07 23:57:00+00,2015-02-08 00:03:00+00,474,5 Ave & E 29 St,40.745168,-73.986831,325,E 19 St & 3 Ave,40.736245,-73.984738,15545,Subscriber,1986.0,1
46198,46199,NaN,NaN,548,2015-02-07 23:58:00+00,2015-02-08 00:08:00+00,368,Carmine St & 6 Ave,40.730386,-74.002150,334,W 20 St & 7 Ave,40.742388,-73.997262,19540,Subscriber,1983.0,2
46199,46200,NaN,NaN,917,2015-02-07 23:59:00+00,2015-02-08 00:15:00+00,439,E 4 St & 2 Ave,40.726281,-73.989780,417,Barclay St & Church St,40.712912,-74.010202,20998,Subscriber,1965.0,2

## Task 1¶
### a. Sort data by start_station_id - only checking trips with duration <= 3 hours
#### 1. the top 10 records

In [11]:
test = '''
SELECT * FROM citibike
WHERE tripduration<10800
ORDER BY start_station_id
LIMIT 10
'''

In [12]:
pd.read_csv(io.BytesIO(queryCartoDB(test)), sep=',')

,cartodb_id,the_geom,the_geom_webmercator,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,3302,NaN,NaN,569,2015-02-01 14:52:00+00,2015-02-01 15:01:00+00,72,W 52 St & 11 Ave,40.767272,-73.993929,499,Broadway & W 60 St,40.769155,-73.981918,17429,Subscriber,1981.0,1
1,1527,NaN,NaN,962,2015-02-01 11:47:00+00,2015-02-01 12:03:00+00,72,W 52 St & 11 Ave,40.767272,-73.993929,212,W 16 St & The High Line,40.743349,-74.006818,16524,Subscriber,1977.0,1
2,2142,NaN,NaN,339,2015-02-01 12:54:00+00,2015-02-01 13:00:00+00,72,W 52 St & 11 Ave,40.767272,-73.993929,478,11 Ave & W 41 St,40.760301,-73.998842,19672,Subscriber,1982.0,1
3,2282,NaN,NaN,301,2015-02-01 13:08:00+00,2015-02-01 13:13:00+00,72,W 52 St & 11 Ave,40.767272,-73.993929,447,8 Ave & W 52 St,40.763707,-73.985162,18174,Subscriber,1974.0,1
4,387,NaN,NaN,961,2015-02-01 08:38:00+00,2015-02-01 08:54:00+00,72,W 52 St & 11 Ave,40.767272,-73.993929,212,W 16 St & The High Line,40.743349,-74.006818,20786,Subscriber,1972.0,2
5,649,NaN,NaN,344,2015-02-01 09:49:00+00,2015-02-01 09:54:00+00,72,W 52 St & 11 Ave,40.767272,-73.993929,2021,W 45 St & 8 Ave,40.759291,-73.988597,14692,Subscriber,1986.0,2
6,1230,NaN,NaN,934,2015-02-01 11:14:00+00,2015-02-01 11:30:00+00,72,W 52 St & 11 Ave,40.767272,-73.993929,212,W 16 St & The High Line,40.743349,-74.006818,17541,Subscriber,1969.0,1
7,1983,NaN,NaN,1944,2015-02-01 12:39:00+00,2015-02-01 13:12:00+00,72,W 52 St & 11 Ave,40.767272,-73.993929,328,Watts St & Greenwich St,40.724055,-74.009660,17849,Customer,NaN,0
8,5136,NaN,NaN,455,2015-02-01 17:55:00+00,2015-02-01 18:03:00+00,72,W 52 St & 11 Ave,40.767272,-73.993929,529,W 42 St & 8 Ave,40.757570,-73.990985,16427,Subscriber,1983.0,1
9,3957,NaN,NaN,387,2015-02-01 15:57:00+00,2015-02-01 16:03:00+00,72,W 52 St & 11 Ave,40.767272,-73.993929,514,12 Ave & W 40 St,40.760875,-74.002777,15282,Subscriber,1991.0,1

#### 2. the last 10 records

In [13]:
test = '''
SELECT * FROM citibike
WHERE tripduration<10800
ORDER BY start_station_id DESC
LIMIT 10
'''

In [14]:
pd.read_csv(io.BytesIO(queryCartoDB(test)), sep=',')

,cartodb_id,the_geom,the_geom_webmercator,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,1228,NaN,NaN,1900,2015-02-01 11:14:00+00,2015-02-01 11:45:00+00,3002,South End Ave & Liberty St,40.711512,-74.015756,525,W 34 St & 11 Ave,40.755942,-74.002116,17849,Customer,NaN,0
1,1863,NaN,NaN,689,2015-02-01 12:25:00+00,2015-02-01 12:36:00+00,3002,South End Ave & Liberty St,40.711512,-74.015756,358,Christopher St & Greenwich St,40.732916,-74.007114,19309,Subscriber,1996.0,1
2,1472,NaN,NaN,683,2015-02-01 11:43:00+00,2015-02-01 11:55:00+00,3002,South End Ave & Liberty St,40.711512,-74.015756,308,St James Pl & Oliver St,40.713079,-73.998512,16987,Subscriber,1980.0,2
3,1506,NaN,NaN,7225,2015-02-01 11:46:00+00,2015-02-01 13:47:00+00,3002,South End Ave & Liberty St,40.711512,-74.015756,499,Broadway & W 60 St,40.769155,-73.981918,21202,Customer,NaN,0
4,1587,NaN,NaN,858,2015-02-01 11:53:00+00,2015-02-01 12:07:00+00,3002,South End Ave & Liberty St,40.711512,-74.015756,355,Bayard St & Baxter St,40.716021,-73.999744,15748,Subscriber,1959.0,1
5,1628,NaN,NaN,745,2015-02-01 11:57:00+00,2015-02-01 12:09:00+00,3002,South End Ave & Liberty St,40.711512,-74.015756,369,Washington Pl & 6 Ave,40.732241,-74.000264,20901,Subscriber,1980.0,1
6,293,NaN,NaN,301,2015-02-01 07:49:00+00,2015-02-01 07:54:00+00,3002,South End Ave & Liberty St,40.711512,-74.015756,417,Barclay St & Church St,40.712912,-74.010202,19484,Subscriber,1980.0,2
7,1333,NaN,NaN,1243,2015-02-01 11:27:00+00,2015-02-01 11:48:00+00,3002,South End Ave & Liberty St,40.711512,-74.015756,360,William St & Pine St,40.707179,-74.008873,18288,Customer,NaN,0
8,2205,NaN,NaN,790,2015-02-01 13:01:00+00,2015-02-01 13:14:00+00,3002,South End Ave & Liberty St,40.711512,-74.015756,368,Carmine St & 6 Ave,40.730386,-74.002150,17004,Subscriber,1979.0,1
9,2026,NaN,NaN,307,2015-02-01 12:42:00+00,2015-02-01 12:47:00+00,3002,South End Ave & Liberty St,40.711512,-74.015756,147,Greenwich St & Warren St,40.715422,-74.011220,18386,Subscriber,1984.0,2

### b. Sort data by tripduration - only checking trips with duration <= 3 hours
#### 1. the top 10 records

In [15]:
test = '''
SELECT * FROM citibike
WHERE tripduration<10800
ORDER BY tripduration
LIMIT 10
'''

In [16]:
pd.read_csv(io.BytesIO(queryCartoDB(test)), sep=',')

,cartodb_id,the_geom,the_geom_webmercator,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,13043,NaN,NaN,60,2015-02-04 06:54:00+00,2015-02-04 06:55:00+00,521,8 Ave & W 31 St,40.750450,-73.994811,521,8 Ave & W 31 St,40.750450,-73.994811,14788,Subscriber,1971,1
1,14117,NaN,NaN,60,2015-02-04 08:41:00+00,2015-02-04 08:42:00+00,296,Division St & Bowery,40.714131,-73.997047,296,Division St & Bowery,40.714131,-73.997047,21644,Subscriber,1990,1
2,8284,NaN,NaN,60,2015-02-03 08:07:00+00,2015-02-03 08:08:00+00,251,Mott St & Prince St,40.723180,-73.994800,251,Mott St & Prince St,40.723180,-73.994800,19896,Subscriber,1982,1
3,11104,NaN,NaN,60,2015-02-03 18:01:00+00,2015-02-03 18:02:00+00,471,Grand St & Havemeyer St,40.712868,-73.956981,471,Grand St & Havemeyer St,40.712868,-73.956981,16340,Subscriber,1980,1
4,3110,NaN,NaN,60,2015-02-01 14:34:00+00,2015-02-01 14:35:00+00,317,E 6 St & Avenue B,40.724537,-73.981854,317,E 6 St & Avenue B,40.724537,-73.981854,20572,Subscriber,1985,1
5,13482,NaN,NaN,60,2015-02-04 07:52:00+00,2015-02-04 07:53:00+00,512,W 29 St & 9 Ave,40.750073,-73.998393,512,W 29 St & 9 Ave,40.750073,-73.998393,21627,Subscriber,1960,2
6,7299,NaN,NaN,60,2015-02-02 17:14:00+00,2015-02-02 17:15:00+00,474,5 Ave & E 29 St,40.745168,-73.986831,474,5 Ave & E 29 St,40.745168,-73.986831,20842,Subscriber,1956,1
7,7798,NaN,NaN,60,2015-02-02 21:39:00+00,2015-02-02 21:40:00+00,379,W 31 St & 7 Ave,40.749156,-73.991600,379,W 31 St & 7 Ave,40.749156,-73.991600,17643,Subscriber,1986,1
8,21407,NaN,NaN,60,2015-02-04 22:38:00+00,2015-02-04 22:39:00+00,523,W 38 St & 8 Ave,40.754666,-73.991382,523,W 38 St & 8 Ave,40.754666,-73.991382,16148,Subscriber,1980,1
9,19243,NaN,NaN,60,2015-02-04 18:22:00+00,2015-02-04 18:23:00+00,248,Laight St & Hudson St,40.721854,-74.007718,248,Laight St & Hudson St,40.721854,-74.007718,20309,Subscriber,1970,1

#### 2. the last 10 records

In [19]:
test = '''
SELECT * FROM citibike
WHERE tripduration<10800
ORDER BY tripduration DESC
LIMIT 10
'''

In [20]:
pd.read_csv(io.BytesIO(queryCartoDB(test)), sep=',')

,cartodb_id,the_geom,the_geom_webmercator,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,41392,NaN,NaN,10757,2015-02-07 12:17:00+00,2015-02-07 15:16:00+00,284,Greenwich Ave & 8 Ave,40.739017,-74.002638,173,Broadway & W 49 St,40.760647,-73.984427,15082,Subscriber,1973,1
1,10912,NaN,NaN,10660,2015-02-03 17:42:00+00,2015-02-03 20:40:00+00,512,W 29 St & 9 Ave,40.750073,-73.998393,435,W 21 St & 6 Ave,40.741740,-73.994156,16099,Subscriber,1950,1
2,40221,NaN,NaN,10174,2015-02-07 09:31:00+00,2015-02-07 12:20:00+00,405,Washington St & Gansevoort St,40.739323,-74.008119,405,Washington St & Gansevoort St,40.739323,-74.008119,21323,Subscriber,1983,1
3,7472,NaN,NaN,9969,2015-02-02 18:22:00+00,2015-02-02 21:08:00+00,386,Centre St & Worth St,40.714948,-74.002345,264,Maiden Ln & Pearl St,40.707065,-74.007319,19921,Subscriber,1987,2
4,9696,NaN,NaN,9938,2015-02-03 14:10:00+00,2015-02-03 16:55:00+00,468,Broadway & W 55 St,40.765265,-73.981923,2023,E 55 St & Lexington Ave,40.759681,-73.970314,19070,Subscriber,1970,1
5,15336,NaN,NaN,9807,2015-02-04 10:53:00+00,2015-02-04 13:36:00+00,435,W 21 St & 6 Ave,40.741740,-73.994156,435,W 21 St & 6 Ave,40.741740,-73.994156,18088,Subscriber,1985,1
6,25203,NaN,NaN,9711,2015-02-05 11:12:00+00,2015-02-05 13:54:00+00,457,Broadway & W 58 St,40.766953,-73.981693,2021,W 45 St & 8 Ave,40.759291,-73.988597,14726,Subscriber,1962,1
7,19897,NaN,NaN,9572,2015-02-04 19:09:00+00,2015-02-04 21:48:00+00,402,Broadway & E 22 St,40.740343,-73.989551,517,Pershing Square South,40.751581,-73.977910,14691,Subscriber,1966,2
8,7073,NaN,NaN,9556,2015-02-02 13:25:00+00,2015-02-02 16:05:00+00,499,Broadway & W 60 St,40.769155,-73.981918,499,Broadway & W 60 St,40.769155,-73.981918,14802,Subscriber,1940,1
9,11810,NaN,NaN,9373,2015-02-03 19:25:00+00,2015-02-03 22:01:00+00,324,DeKalb Ave & Hudson Ave,40.689888,-73.981013,324,DeKalb Ave & Hudson Ave,40.689888,-73.981013,15018,Subscriber,1968,1

### c. List all unique start_station_id values

In [21]:
test = '''
SELECT DISTINCT start_station_id FROM citibike
ORDER BY start_station_id
'''

In [22]:
pd.read_csv(io.BytesIO(queryCartoDB(test)), sep=',')

     start_station_id  Unnamed: 1
0                  72         NaN
1                  79         NaN
2                  82         NaN
3                  83         NaN
4                 116         NaN
5                 119         NaN
6                 120         NaN
7                 127         NaN
8                 128         NaN
9                 137         NaN
10                143         NaN
11                144         NaN
12                146         NaN
13                147         NaN
14                150         NaN
15                151         NaN
16                152         NaN
17                153         NaN
18                157         NaN
19                160         NaN
20                161         NaN
21                164         NaN
22                167         NaN
23                168         NaN
24                173         NaN
25                174         NaN
26                195         NaN
27                212         NaN
28                216         NaN
29                217         NaN
..                ...         ...
297               525         NaN
298               526         NaN
299               527         NaN
300               528         NaN
301               529         NaN
302               530         NaN
303               531         NaN
304               532         NaN
305               533         NaN
306               534         NaN
307               537         NaN
308               538         NaN
309               539         NaN
310               545         NaN
311               546         NaN
312              2000         NaN
313              2001         NaN
314              2002         NaN
315              2004         NaN
316              2005         NaN
317              2006         NaN
318              2008         NaN
319              2009         NaN
320              2010         NaN
321              2012         NaN
322              2017         NaN
323              2021         NaN
324              2022         NaN
325              2023         NaN
326              3002         NaN

[327 rows x 2 columns]

### d. Count the number/average/min/max of trips

In [24]:
test = '''
SELECT COUNT(tripduration) as numtrips,
       AVG(tripduration) as avgtrips,
       MIN(tripduration) as mintrips,
       MAX(tripduration) as maxtrips
FROM citibike
'''

In [25]:
pd.read_csv(io.BytesIO(queryCartoDB(test)), sep=',')

   numtrips    avgtrips  mintrips  maxtrips
0     46200  675.865823        60     43016

## Task 2
### a. Selecting trips started on Feb-02-2015 only

In [27]:
test = '''
SELECT * FROM citibike
WHERE starttime >= '2015-02-02 00:00'
AND   starttime  < '2015-02-03 00:00'
'''

In [28]:
pd.read_csv(io.BytesIO(queryCartoDB(test)), sep=',')

,cartodb_id,the_geom,the_geom_webmercator,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,6442,NaN,NaN,199,2015-02-02 00:02:00+00,2015-02-02 00:05:00+00,442,W 27 St & 7 Ave,40.746647,-73.993915,489,10 Ave & W 28 St,40.750664,-74.001768,20684,Subscriber,1992.0,1
1,6443,NaN,NaN,418,2015-02-02 00:03:00+00,2015-02-02 00:10:00+00,326,E 11 St & 1 Ave,40.729538,-73.984267,349,Rivington St & Ridge St,40.718502,-73.983299,16094,Subscriber,1964.0,2
2,6444,NaN,NaN,276,2015-02-02 00:04:00+00,2015-02-02 00:09:00+00,279,Peck Slip & Front St,40.707873,-74.001670,415,Pearl St & Hanover Square,40.704718,-74.009260,17362,Subscriber,1974.0,1
3,6445,NaN,NaN,420,2015-02-02 00:06:00+00,2015-02-02 00:13:00+00,496,E 16 St & 5 Ave,40.737262,-73.992390,237,E 11 St & 2 Ave,40.730473,-73.986724,15475,Subscriber,1992.0,2
4,6446,NaN,NaN,304,2015-02-02 00:07:00+00,2015-02-02 00:12:00+00,477,W 41 St & 8 Ave,40.756405,-73.990026,450,W 49 St & 8 Ave,40.762272,-73.987882,16272,Subscriber,1968.0,1
5,6447,NaN,NaN,622,2015-02-02 00:08:00+00,2015-02-02 00:18:00+00,467,Dean St & 4 Ave,40.683125,-73.978951,391,Clark St & Henry St,40.697601,-73.993446,16370,Subscriber,1979.0,1
6,6448,NaN,NaN,371,2015-02-02 00:09:00+00,2015-02-02 00:15:00+00,434,9 Ave & W 18 St,40.743174,-74.003664,482,W 15 St & 7 Ave,40.739355,-73.999318,19437,Subscriber,1963.0,1
7,6449,NaN,NaN,477,2015-02-02 00:11:00+00,2015-02-02 00:19:00+00,330,Reade St & Broadway,40.714505,-74.005628,2008,Little West St & 1 Pl,40.705693,-74.016777,21211,Subscriber,1982.0,1
8,6450,NaN,NaN,743,2015-02-02 00:12:00+00,2015-02-02 00:25:00+00,521,8 Ave & W 31 St,40.750450,-73.994811,423,W 54 St & 9 Ave,40.765849,-73.986905,21417,Subscriber,1978.0,2
9,6451,NaN,NaN,599,2015-02-02 00:12:00+00,2015-02-02 00:22:00+00,504,1 Ave & E 15 St,40.732219,-73.981656,453,W 22 St & 8 Ave,40.744751,-73.999154,15722,Subscriber,1956.0,1
10,6452,NaN,NaN,345,2015-02-02 00:12:00+00,2015-02-02 00:18:00+00,285,Broadway & E 14 St,40.734546,-73.990741,236,St Marks Pl & 2 Ave,40.728419,-73.987140,18972,Subscriber,1962.0,1
11,6453,NaN,NaN,721,2015-02-02 00:13:00+00,2015-02-02 00:25:00+00,301,E 2 St & Avenue B,40.722174,-73.983688,476,E 31 St & 3 Ave,40.743943,-73.979661,19628,Subscriber,1980.0,1
12,6454,NaN,NaN,182,2015-02-02 00:13:00+00,2015-02-02 00:16:00+00,279,Peck Slip & Front St,40.707873,-74.001670,376,John St & William St,40.708621,-74.007222,15169,Subscriber,1978.0,1
13,6455,NaN,NaN,154,2015-02-02 00:13:00+00,2015-02-02 00:16:00+00,342,Columbia St & Rivington St,40.717400,-73.980166,411,E 6 St & Avenue D,40.722281,-73.976687,17533,Subscriber,1997.0,1
14,6456,NaN,NaN,435,2015-02-02 00:14:00+00,2015-02-02 00:21:00+00,470,W 20 St & 8 Ave,40.743453,-74.000040,491,E 24 St & Park Ave S,40.740964,-73.986022,19761,Subscriber,1983.0,1
15,6457,NaN,NaN,310,2015-02-02 00:15:00+00,2015-02-02 00:20:00+00,236,St Marks Pl & 2 Ave,40.728419,-73.987140,393,E 5 St & Avenue C,40.722992,-73.979955,17267,Subscriber,1993.0,1
16,6458,NaN,NaN,1274,2015-02-02 00:16:00+00,2015-02-02 00:37:00+00,470,W 20 St & 8 Ave,40.743453,-74.000040,470,W 20 St & 8 Ave,40.743453,-74.000040,18691,Subscriber,1964.0,1
17,6459,NaN,NaN,642,2015-02-02 00:18:00+00,2015-02-02 00:29:00+00,485,W 37 St & 5 Ave,40.750380,-73.983390,174,E 25 St & 1 Ave,40.738177,-73.977387,17106,Subscriber,1977.0,1
18,6460,NaN,NaN,256,2015-02-02 00:18:00+00,2015-02-02 00:22:00+00,345,W 13 St & 6 Ave,40.736494,-73.997044,483,E 12 St & 3 Ave,40.732233,-73.988900,20009,Subscriber,1973.0,1
19,6461,NaN,NaN,334,2015-02-02 00:19:00+00,2015-02-02 00:25:00+00,489,10 Ave & W 28 St,40.750664,-74.001768,442,W 27 St & 7 Ave,40.746647,-73.993915,18777,Subscriber,1979.0,1
20,6462,NaN,NaN,90,2015-02-02 00:19:00+00,2015-02-02 00:20:00+00,507,E 25 St & 2 Ave,40.739126,-73.979738,174,E 25 St & 1 Ave,40.738177,-73.977387,15357,Subscriber,1989.0,1
21,6463,NaN,NaN,203,2015-02-02 00:20:00+00,2015-02-02 00:23:00+00,380,W 4 St & 7 Ave S,40.734011,-74.002939,405,Washington St & Gansevoort St,40.739323,-74.008119,18487,Subscriber,1983.0,1
22,6464,NaN,NaN,649,2015-02-02 00:22:00+00,2015-02-02 00:32:00+00,334,W 20 St & 7 Ave,40.742388,-73.997262,439,E 4 St & 2 Ave,40.726281,-73.989780,20863,Subscriber,1981.0,1
23,6465,NaN,NaN,319,2015-02-02 00:23:00+00,2015-02-02 00:29:00+00,508,W 46 St & 11 Ave,40.763414,-73.996674,448,W 37 St & 10 Ave,40.756604,-73.997901,16539,Subscriber,1970.0,1
24,6466,NaN,NaN,154,2015-02-02 00:27:00+00,2015-02-02 00:30:00+00,428,E 3 St & 1 Ave,40.724677,-73.987834,301,E 2 St & Avenue B,40.722174,-73.983688,18737,Subscriber,1961.0,1
25,6467,NaN,NaN,550,2015-02-02 00:28:00+00,2015-02-02 00:37:00+00,331,Pike St & Monroe St,40.711731,-73.991930,195,Liberty St & Broadway,40.709056,-74.010434,17797,Subscriber,1980.0,2
26,6468,NaN,NaN,268,2015-02-02 00:29:00+00,2015-02-02 00:34:00+00,529,W 42 St & 8 Ave,40.757570,-73.990985,478,11 Ave & W 41 St,40.760301,-73.998842,20638,Subscriber,1990.0,1
27,6469,NaN,NaN,153,2015-02-02 00:29:00+00,2015-02-02 00:31:00+00,421,Clermont Ave & Park Ave,40.695734,-73.971297,366,Clinton Ave & Myrtle Ave,40.693261,-73.968896,17636,Subscriber,1989.0,1
28,6470,NaN,NaN,309,2015-02-02 00:31:00+00,2015-02-02 00:36:00+00,284,Greenwich Ave & 8 Ave,40.739017,-74.002638,494,W 26 St & 8 Ave,40.747348,-73.997236,18472,Subscriber,1982.0,1
29,6471,NaN,NaN,138,2015-02-02 00:33:00+00,2015-02-02 00:35:00+00,383,Greenwich Ave & Charles St,40.735238,-74.000271,252,MacDougal St & Washington Sq,40.732264,-73.998522,17456,Subscriber,1968.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1429,7871,NaN,NaN,722,2015-02-02 23:08:00+00,2015-02-02 23:20:00+00,312,Allen St & E Houston St,40.722055,-73.989111,380,W 4 St & 7 Ave S,40.734011,-74.002939,20572,Subscriber,1985.0,1
1430,7872,NaN,NaN,274,2015-02-02 23:08:00+00,2015-02-02 23:12:00+00,486,Broadway & W 29 St,40.746201,-73.988557,491,E 24 St & Park Ave S,40.740964,-73.986022,20338,Subscriber,1981.0,1
1431,7873,NaN,NaN,951,2015-02-02 23:11:00+00,2015-02-02 23:27:00+00,352,W 56 St & 6 Ave,40.763406,-73.977225,515,W 43 St & 10 Ave,40.760094,-73.994618,15826,Subscriber,1978.0,1
1432,7874,NaN,NaN,276,2015-02-02 23:16:00+00,2015-02-02 23:20:00+00,489,10 Ave & W 28 St,40.750664,-74.001768,521,8 Ave & W 31 St,40.750450,-73.994811,18325,Subscriber,1990.0,1
1433,7875,NaN,NaN,426,2015-02-02 23:17:00+00,2015-02-02 23:24:00+00,494,W 26 St & 8 Ave,40.747348,-73.997236,434,9 Ave & W 18 St,40.743174,-74.003664,16654,Subscriber,1977.0,1
1434,7876,NaN,NaN,578,2015-02-02 23:19:00+00,2015-02-02 23:28:00+00,402,Broadway & E 22 St,40.740343,-73.989551,229,Great Jones St,40.727434,-73.993790,20902,Subscriber,1966.0,1
1435,7877,NaN,NaN,2621,2015-02-02 23:22:00+00,2015-02-03 00:06:00+00,164,E 47 St & 2 Ave,40.753231,-73.970325,2017,E 43 St & 2 Ave,40.750224,-73.971214,20796,Subscriber,1954.0,1
1436,7878,NaN,NaN,621,2015-02-02 23:22:00+00,2015-02-02 23:32:00+00,498,Broadway & W 32 St,40.748549,-73.988084,449,W 52 St & 9 Ave,40.764618,-73.987895,20160,Subscriber,1989.0,1
1437,7879,NaN,NaN,323,2015-02-02 23:23:00+00,2015-02-02 23:29:00+00,521,8 Ave & W 31 St,40.750450,-73.994811,477,W 41 St & 8 Ave,40.756405,-73.990026,17392,Subscriber,1974.0,1
1438,7880,NaN,NaN,393,2015-02-02 23:24:00+00,2015-02-02 23:31:00+00,434,9 Ave & W 18 St,40.743174,-74.003664,482,W 15 St & 7 Ave,40.739355,-73.999318,17263,Subscriber,1963.0,1
1439,7881,NaN,NaN,597,2015-02-02 23:25:00+00,2015-02-02 23:35:00+00,161,LaGuardia Pl & W 3 St,40.729170,-73.998102,497,E 17 St & Broadway,40.737050,-73.990093,19858,Subscriber,1955.0,1
1440,7882,NaN,NaN,244,2015-02-02 23:25:00+00,2015-02-02 23:30:00+00,494,W 26 St & 8 Ave,40.747348,-73.997236,462,W 22 St & 10 Ave,40.746920,-74.004519,20319,Subscriber,1979.0,1
1441,7883,NaN,NaN,1023,2015-02-02 23:26:00+00,2015-02-02 23:43:00+00,306,Cliff St & Fulton St,40.708235,-74.005301,127,Barrow St & Hudson St,40.731724,-74.006744,21600,Subscriber,1977.0,1
1442,7884,NaN,NaN,419,2015-02-02 23:31:00+00,2015-02-02 23:38:00+00,349,Rivington St & Ridge St,40.718502,-73.983299,473,Rivington St & Chrystie St,40.721101,-73.991925,18791,Subscriber,1986.0,1
1443,7885,NaN,NaN,1429,2015-02-02 23:32:00+00,2015-02-02 23:55:00+00,450,W 49 St & 8 Ave,40.762272,-73.987882,358,Christopher St & Greenwich St,40.732916,-74.007114,17730,Subscriber,1966.0,1
1444,7886,NaN,NaN,676,2015-02-02 23:32:00+00,2015-02-02 23:44:00+00,519,Pershing Square North,40.751873,-73.977706,477,W 41 St & 8 Ave,40.756405,-73.990026,18147,Subscriber,1980.0,1
1445,7887,NaN,NaN,879,2015-02-02 23:33:00+00,2015-02-02 23:48:00+00,546,E 30 St & Park Ave S,40.744449,-73.983035,489,10 Ave & W 28 St,40.750664,-74.001768,20249,Subscriber,1959.0,1
1446,7888,NaN,NaN,593,2015-02-02 23:35:00+00,2015-02-02 23:45:00+00,336,Sullivan St & Washington Sq,40.730477,-73.999061,432,E 7 St & Avenue A,40.726218,-73.983799,18078,Subscriber,1988.0,1
1447,7889,NaN,NaN,839,2015-02-02 23:36:00+00,2015-02-02 23:50:00+00,529,W 42 St & 8 Ave,40.757570,-73.990985,164,E 47 St & 2 Ave,40.753231,-73.970325,16808,Subscriber,1983.0,1
1448,7890,NaN,NaN,560,2015-02-02 23:37:00+00,2015-02-02 23:46:00+00,402,Broadway & E 22 St,40.740343,-73.989551,368,Carmine St & 6 Ave,40.730386,-74.002150,21355,Subscriber,1986.0,1
1449,7891,NaN,NaN,165,2015-02-02 23:37:00+00,2015-02-02 23:40:00+00,504,1 Ave & E 15 St,40.732219,-73.981656,511,E 14 St & Avenue B,40.729387,-73.977724,15359,Subscriber,1994.0,1
1450,7892,NaN,NaN,813,2015-02-02 23:42:00+00,2015-02-02 23:56:00+00,505,6 Ave & W 33 St,40.749013,-73.988484,489,10 Ave & W 28 St,40.750664,-74.001768,18250,Subscriber,1982.0,2
1451,7893,NaN,NaN,764,2015-02-02 23:42:00+00,2015-02-02 23:55:00+00,509,9 Ave & W 22 St,40.745497,-74.001971,507,E 25 St & 2 Ave,40.739126,-73.979738,16969,Subscriber,1987.0,1
1452,7894,NaN,NaN,2111,2015-02-02 23:43:00+00,2015-02-03 00:18:00+00,496,E 16 St & 5 Ave,40.737262,-73.992390,397,Fulton St & Clermont Ave,40.684157,-73.969223,18825,Subscriber,1979.0,1
1453,7895,NaN,NaN,518,2015-02-02 23:43:00+00,2015-02-02 23:52:00+00,280,E 10 St & 5 Ave,40.733320,-73.995101,439,E 4 St & 2 Ave,40.726281,-73.989780,19000,Subscriber,1983.0,1
1454,7896,NaN,NaN,371,2015-02-02 23:45:00+00,2015-02-02 23:52:00+00,484,W 44 St & 5 Ave,40.755003,-73.980144,440,E 45 St & 3 Ave,40.752554,-73.972826,20723,Subscriber,1977.0,1
1455,7897,NaN,NaN,188,2015-02-02 23:47:00+00,2015-02-02 23:50:00+00,224,Spruce St & Nassau St,40.711464,-74.005524,417,Barclay St & Church St,40.712912,-74.010202,16528,Subscriber,1988.0,1
1456,7898,NaN,NaN,689,2015-02-02 23:50:00+00,2015-02-03 00:02:00+00,345,W 13 St & 6 Ave,40.736494,-73.997044,394,E 9 St & Avenue C,40.725213,-73.977688,16541,Subscriber,1988.0,1
1457,7899,NaN,NaN,634,2015-02-02 23:55:00+00,2015-02-03 00:05:00+00,453,W 22 St & 8 Ave,40.744751,-73.999154,537,Lexington Ave & E 24 St,40.740259,-73.984092,14878,Subscriber,1961.0,1
1458,7900,NaN,NaN,733,2015-02-02 23:58:00+00,2015-02-03 00:10:00+00,285,Broadway & E 14 St,40.734546,-73.990741,302,Avenue D & E 3 St,40.720828,-73.977932,16326,Subscriber,1976.0,2

### b. Selecting trips started on the weekends and calculate the average trip duration during weekends

In [29]:
test = '''
SELECT * FROM citibike
WHERE extract(DOW FROM starttime) in (0,6)
'''

In [30]:
pd.read_csv(io.BytesIO(queryCartoDB(test)), sep=',')

,cartodb_id,the_geom,the_geom_webmercator,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,5960,NaN,NaN,351,2015-02-01 20:36:00+00,2015-02-01 20:42:00+00,435,W 21 St & 6 Ave,40.741740,-73.994156,462,W 22 St & 10 Ave,40.746920,-74.004519,19217,Subscriber,1965.0,1
1,1,NaN,NaN,801,2015-02-01 00:00:00+00,2015-02-01 00:14:00+00,521,8 Ave & W 31 St,40.750450,-73.994811,423,W 54 St & 9 Ave,40.765849,-73.986905,17131,Subscriber,1978.0,2
2,2,NaN,NaN,379,2015-02-01 00:00:00+00,2015-02-01 00:07:00+00,497,E 17 St & Broadway,40.737050,-73.990093,504,1 Ave & E 15 St,40.732219,-73.981656,21289,Subscriber,1993.0,1
3,3,NaN,NaN,2474,2015-02-01 00:01:00+00,2015-02-01 00:42:00+00,281,Grand Army Plaza & Central Park S,40.764397,-73.973715,127,Barrow St & Hudson St,40.731724,-74.006744,18903,Subscriber,1969.0,2
4,4,NaN,NaN,818,2015-02-01 00:01:00+00,2015-02-01 00:15:00+00,2004,6 Ave & Broome St,40.724399,-74.004704,505,6 Ave & W 33 St,40.749013,-73.988484,21044,Subscriber,1985.0,2
5,5,NaN,NaN,544,2015-02-01 00:01:00+00,2015-02-01 00:10:00+00,323,Lawrence St & Willoughby St,40.692362,-73.986317,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,19868,Subscriber,1957.0,1
6,6,NaN,NaN,717,2015-02-01 00:02:00+00,2015-02-01 00:14:00+00,373,Willoughby Ave & Walworth St,40.693317,-73.953820,2002,Wythe Ave & Metropolitan Ave,40.716887,-73.963198,15854,Subscriber,1979.0,1
7,7,NaN,NaN,1306,2015-02-01 00:04:00+00,2015-02-01 00:26:00+00,352,W 56 St & 6 Ave,40.763406,-73.977225,504,1 Ave & E 15 St,40.732219,-73.981656,15173,Subscriber,1983.0,1
8,8,NaN,NaN,913,2015-02-01 00:04:00+00,2015-02-01 00:19:00+00,439,E 4 St & 2 Ave,40.726281,-73.989780,116,W 17 St & 8 Ave,40.741776,-74.001497,17862,Subscriber,1955.0,1
9,9,NaN,NaN,759,2015-02-01 00:04:00+00,2015-02-01 00:17:00+00,335,Washington Pl & Broadway,40.729039,-73.994046,2012,E 27 St & 1 Ave,40.739445,-73.976806,21183,Subscriber,1985.0,2
10,10,NaN,NaN,585,2015-02-01 00:05:00+00,2015-02-01 00:15:00+00,284,Greenwich Ave & 8 Ave,40.739017,-74.002638,444,Broadway & W 24 St,40.742354,-73.989151,14843,Subscriber,1982.0,1
11,11,NaN,NaN,581,2015-02-01 00:05:00+00,2015-02-01 00:15:00+00,284,Greenwich Ave & 8 Ave,40.739017,-74.002638,444,Broadway & W 24 St,40.742354,-73.989151,16936,Subscriber,1988.0,2
12,12,NaN,NaN,204,2015-02-01 00:05:00+00,2015-02-01 00:08:00+00,498,Broadway & W 32 St,40.748549,-73.988084,472,E 32 St & Park Ave,40.745712,-73.981948,21507,Subscriber,1991.0,2
13,13,NaN,NaN,1169,2015-02-01 00:07:00+00,2015-02-01 00:27:00+00,368,Carmine St & 6 Ave,40.730386,-74.002150,307,Canal St & Rutgers St,40.714275,-73.989900,17456,Subscriber,1982.0,2
14,14,NaN,NaN,419,2015-02-01 00:07:00+00,2015-02-01 00:14:00+00,326,E 11 St & 1 Ave,40.729538,-73.984267,2012,E 27 St & 1 Ave,40.739445,-73.976806,14679,Subscriber,1990.0,2
15,15,NaN,NaN,527,2015-02-01 00:09:00+00,2015-02-01 00:17:00+00,285,Broadway & E 14 St,40.734546,-73.990741,212,W 16 St & The High Line,40.743349,-74.006818,18978,Subscriber,1977.0,1
16,16,NaN,NaN,1013,2015-02-01 00:10:00+00,2015-02-01 00:27:00+00,368,Carmine St & 6 Ave,40.730386,-74.002150,488,W 39 St & 9 Ave,40.756458,-73.993722,16496,Subscriber,1968.0,1
17,17,NaN,NaN,587,2015-02-01 00:13:00+00,2015-02-01 00:23:00+00,394,E 9 St & Avenue C,40.725213,-73.977688,331,Pike St & Monroe St,40.711731,-73.991930,17107,Subscriber,1990.0,1
18,18,NaN,NaN,525,2015-02-01 00:13:00+00,2015-02-01 00:22:00+00,326,E 11 St & 1 Ave,40.729538,-73.984267,507,E 25 St & 2 Ave,40.739126,-73.979738,16984,Subscriber,1987.0,1
19,19,NaN,NaN,670,2015-02-01 00:14:00+00,2015-02-01 00:26:00+00,493,W 45 St & 6 Ave,40.756800,-73.982912,305,E 58 St & 3 Ave,40.760958,-73.967245,15997,Subscriber,1980.0,1
20,20,NaN,NaN,711,2015-02-01 00:15:00+00,2015-02-01 00:27:00+00,445,E 10 St & Avenue A,40.727408,-73.981420,223,W 13 St & 7 Ave,40.737815,-73.999947,21516,Subscriber,1960.0,1
21,21,NaN,NaN,1559,2015-02-01 00:16:00+00,2015-02-01 00:42:00+00,428,E 3 St & 1 Ave,40.724677,-73.987834,457,Broadway & W 58 St,40.766953,-73.981693,15815,Subscriber,1986.0,1
22,22,NaN,NaN,683,2015-02-01 00:16:00+00,2015-02-01 00:27:00+00,228,E 48 St & 3 Ave,40.754601,-73.971879,477,W 41 St & 8 Ave,40.756405,-73.990026,18727,Subscriber,1987.0,1
23,23,NaN,NaN,522,2015-02-01 00:16:00+00,2015-02-01 00:24:00+00,513,W 56 St & 10 Ave,40.768254,-73.988639,488,W 39 St & 9 Ave,40.756458,-73.993722,14982,Subscriber,1969.0,1
24,24,NaN,NaN,389,2015-02-01 00:16:00+00,2015-02-01 00:23:00+00,507,E 25 St & 2 Ave,40.739126,-73.979738,518,E 39 St & 2 Ave,40.747804,-73.973442,16391,Subscriber,1957.0,1
25,25,NaN,NaN,276,2015-02-01 00:16:00+00,2015-02-01 00:21:00+00,439,E 4 St & 2 Ave,40.726281,-73.989780,473,Rivington St & Chrystie St,40.721101,-73.991925,15947,Subscriber,1981.0,1
26,26,NaN,NaN,907,2015-02-01 00:17:00+00,2015-02-01 00:32:00+00,128,MacDougal St & Prince St,40.727103,-74.002971,531,Forsyth St & Broome St,40.718939,-73.992663,16917,Subscriber,1993.0,1
27,27,NaN,NaN,946,2015-02-01 00:18:00+00,2015-02-01 00:33:00+00,490,8 Ave & W 33 St,40.751551,-73.993934,528,2 Ave & E 31 St,40.742909,-73.977061,15924,Subscriber,1975.0,1
28,28,NaN,NaN,144,2015-02-01 00:18:00+00,2015-02-01 00:21:00+00,350,Clinton St & Grand St,40.715595,-73.987030,502,Henry St & Grand St,40.714215,-73.981346,21321,Subscriber,1973.0,1
29,29,NaN,NaN,257,2015-02-01 00:19:00+00,2015-02-01 00:23:00+00,250,Lafayette St & Jersey St,40.724561,-73.995653,401,Allen St & Rivington St,40.720196,-73.989978,16861,Subscriber,1973.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13201,46171,NaN,NaN,812,2015-02-07 23:51:00+00,2015-02-08 00:05:00+00,335,Washington Pl & Broadway,40.729039,-73.994046,435,W 21 St & 6 Ave,40.741740,-73.994156,15733,Subscriber,1988.0,1
13202,46172,NaN,NaN,647,2015-02-07 23:51:00+00,2015-02-08 00:02:00+00,361,Allen St & Hester St,40.716059,-73.991908,504,1 Ave & E 15 St,40.732219,-73.981656,16931,Subscriber,1995.0,1
13203,46173,NaN,NaN,563,2015-02-07 23:51:00+00,2015-02-08 00:00:00+00,152,Warren St & Church St,40.714740,-74.009106,401,Allen St & Rivington St,40.720196,-73.989978,17202,Subscriber,1987.0,1
13204,46174,NaN,NaN,470,2015-02-07 23:51:00+00,2015-02-07 23:59:00+00,483,E 12 St & 3 Ave,40.732233,-73.988900,439,E 4 St & 2 Ave,40.726281,-73.989780,20314,Subscriber,1989.0,2
13205,46175,NaN,NaN,299,2015-02-07 23:51:00+00,2015-02-07 23:56:00+00,467,Dean St & 4 Ave,40.683125,-73.978951,395,Bond St & Schermerhorn St,40.688070,-73.984106,21531,Subscriber,1989.0,1
13206,46176,NaN,NaN,629,2015-02-07 23:52:00+00,2015-02-08 00:02:00+00,361,Allen St & Hester St,40.716059,-73.991908,504,1 Ave & E 15 St,40.732219,-73.981656,21491,Subscriber,1968.0,1
13207,46177,NaN,NaN,499,2015-02-07 23:52:00+00,2015-02-08 00:00:00+00,402,Broadway & E 22 St,40.740343,-73.989551,380,W 4 St & 7 Ave S,40.734011,-74.002939,15367,Subscriber,1990.0,1
13208,46178,NaN,NaN,474,2015-02-07 23:52:00+00,2015-02-08 00:00:00+00,369,Washington Pl & 6 Ave,40.732241,-74.000264,368,Carmine St & 6 Ave,40.730386,-74.002150,18978,Subscriber,1973.0,2
13209,46179,NaN,NaN,345,2015-02-07 23:52:00+00,2015-02-07 23:58:00+00,476,E 31 St & 3 Ave,40.743943,-73.979661,504,1 Ave & E 15 St,40.732219,-73.981656,19507,Subscriber,1980.0,1
13210,46180,NaN,NaN,829,2015-02-07 23:53:00+00,2015-02-08 00:07:00+00,499,Broadway & W 60 St,40.769155,-73.981918,160,E 37 St & Lexington Ave,40.748238,-73.978311,16936,Subscriber,1980.0,1
13211,46181,NaN,NaN,776,2015-02-07 23:53:00+00,2015-02-08 00:05:00+00,368,Carmine St & 6 Ave,40.730386,-74.002150,531,Forsyth St & Broome St,40.718939,-73.992663,18689,Subscriber,1982.0,1
13212,46182,NaN,NaN,697,2015-02-07 23:53:00+00,2015-02-08 00:05:00+00,520,W 52 St & 5 Ave,40.759923,-73.976485,478,11 Ave & W 41 St,40.760301,-73.998842,15781,Subscriber,1972.0,1
13213,46183,NaN,NaN,1703,2015-02-07 23:54:00+00,2015-02-08 00:23:00+00,467,Dean St & 4 Ave,40.683125,-73.978951,471,Grand St & Havemeyer St,40.712868,-73.956981,15081,Subscriber,1988.0,1
13214,46184,NaN,NaN,922,2015-02-07 23:54:00+00,2015-02-08 00:10:00+00,479,9 Ave & W 45 St,40.760193,-73.991255,247,Perry St & Bleecker St,40.735354,-74.004831,21672,Subscriber,1983.0,1
13215,46185,NaN,NaN,849,2015-02-07 23:54:00+00,2015-02-08 00:08:00+00,457,Broadway & W 58 St,40.766953,-73.981693,488,W 39 St & 9 Ave,40.756458,-73.993722,16336,Subscriber,1970.0,1
13216,46186,NaN,NaN,826,2015-02-07 23:54:00+00,2015-02-08 00:08:00+00,457,Broadway & W 58 St,40.766953,-73.981693,488,W 39 St & 9 Ave,40.756458,-73.993722,21609,Subscriber,1973.0,1
13217,46187,NaN,NaN,473,2015-02-07 23:54:00+00,2015-02-08 00:02:00+00,328,Watts St & Greenwich St,40.724055,-74.009660,3002,South End Ave & Liberty St,40.711512,-74.015756,19470,Subscriber,1964.0,1
13218,46188,NaN,NaN,332,2015-02-07 23:54:00+00,2015-02-07 23:59:00+00,510,W 51 St & 6 Ave,40.760660,-73.980420,450,W 49 St & 8 Ave,40.762272,-73.987882,18167,Subscriber,1960.0,1
13219,46189,NaN,NaN,456,2015-02-07 23:55:00+00,2015-02-08 00:03:00+00,382,University Pl & E 14 St,40.734927,-73.992005,404,9 Ave & W 14 St,40.740583,-74.005509,15929,Subscriber,1987.0,1
13220,46190,NaN,NaN,327,2015-02-07 23:55:00+00,2015-02-08 00:01:00+00,254,W 11 St & 6 Ave,40.735324,-73.998004,466,W 25 St & 6 Ave,40.743954,-73.991449,17541,Subscriber,1983.0,1
13221,46191,NaN,NaN,306,2015-02-07 23:55:00+00,2015-02-08 00:01:00+00,116,W 17 St & 8 Ave,40.741776,-74.001497,494,W 26 St & 8 Ave,40.747348,-73.997236,14736,Subscriber,1983.0,2
13222,46192,NaN,NaN,1248,2015-02-07 23:56:00+00,2015-02-08 00:17:00+00,495,W 47 St & 10 Ave,40.762699,-73.993012,432,E 7 St & Avenue A,40.726218,-73.983799,16300,Subscriber,1984.0,1
13223,46193,NaN,NaN,1165,2015-02-07 23:56:00+00,2015-02-08 00:15:00+00,152,Warren St & Church St,40.714740,-74.009106,325,E 19 St & 3 Ave,40.736245,-73.984738,16978,Subscriber,1959.0,1
13224,46194,NaN,NaN,993,2015-02-07 23:56:00+00,2015-02-08 00:13:00+00,461,E 20 St & 2 Ave,40.735877,-73.982050,295,Pike St & E Broadway,40.714067,-73.992939,16722,Subscriber,1974.0,1
13225,46195,NaN,NaN,1422,2015-02-07 23:57:00+00,2015-02-08 00:20:00+00,455,1 Ave & E 44 St,40.750020,-73.969053,265,Stanton St & Chrystie St,40.722293,-73.991475,20184,Subscriber,1960.0,2
13226,46196,NaN,NaN,689,2015-02-07 23:57:00+00,2015-02-08 00:08:00+00,470,W 20 St & 8 Ave,40.743453,-74.000040,325,E 19 St & 3 Ave,40.736245,-73.984738,15585,Subscriber,1953.0,1
13227,46197,NaN,NaN,428,2015-02-07 23:57:00+00,2015-02-08 00:04:00+00,474,5 Ave & E 29 St,40.745168,-73.986831,325,E 19 St & 3 Ave,40.736245,-73.984738,16395,Subscriber,1986.0,2
13228,46198,NaN,NaN,392,2015-02-07 23:57:00+00,2015-02-08 00:03:00+00,474,5 Ave & E 29 St,40.745168,-73.986831,325,E 19 St & 3 Ave,40.736245,-73.984738,15545,Subscriber,1986.0,1
13229,46199,NaN,NaN,548,2015-02-07 23:58:00+00,2015-02-08 00:08:00+00,368,Carmine St & 6 Ave,40.730386,-74.002150,334,W 20 St & 7 Ave,40.742388,-73.997262,19540,Subscriber,1983.0,2
13230,46200,NaN,NaN,917,2015-02-07 23:59:00+00,2015-02-08 00:15:00+00,439,E 4 St & 2 Ave,40.726281,-73.989780,417,Barclay St & Church St,40.712912,-74.010202,20998,Subscriber,1965.0,2

In [31]:
test = '''
SELECT AVG(tripduration) as avgtrips FROM citibike
WHERE extract(DOW FROM starttime) in (0,6)
'''

In [32]:
pd.read_csv(io.BytesIO(queryCartoDB(test)), sep=',')

     avgtrips  Unnamed: 1
0  662.942181         NaN

So the average trip duration time during weekends is 662.94 s

### c. do the same for weekday

In [35]:
test = '''
SELECT * FROM citibike
WHERE extract(DOW FROM starttime) not in (0,6)
'''

In [36]:
pd.read_csv(io.BytesIO(queryCartoDB(test)), sep=',')

,cartodb_id,the_geom,the_geom_webmercator,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,9806,NaN,NaN,643,2015-02-03 14:39:00+00,2015-02-03 14:50:00+00,167,E 39 St & 3 Ave,40.748901,-73.976049,488,W 39 St & 9 Ave,40.756458,-73.993722,17575,Subscriber,1971.0,1
1,13113,NaN,NaN,1379,2015-02-04 07:07:00+00,2015-02-04 07:30:00+00,332,Cherry St,40.712199,-73.979481,440,E 45 St & 3 Ave,40.752554,-73.972826,20313,Subscriber,1973.0,1
2,6442,NaN,NaN,199,2015-02-02 00:02:00+00,2015-02-02 00:05:00+00,442,W 27 St & 7 Ave,40.746647,-73.993915,489,10 Ave & W 28 St,40.750664,-74.001768,20684,Subscriber,1992.0,1
3,6443,NaN,NaN,418,2015-02-02 00:03:00+00,2015-02-02 00:10:00+00,326,E 11 St & 1 Ave,40.729538,-73.984267,349,Rivington St & Ridge St,40.718502,-73.983299,16094,Subscriber,1964.0,2
4,6444,NaN,NaN,276,2015-02-02 00:04:00+00,2015-02-02 00:09:00+00,279,Peck Slip & Front St,40.707873,-74.001670,415,Pearl St & Hanover Square,40.704718,-74.009260,17362,Subscriber,1974.0,1
5,6445,NaN,NaN,420,2015-02-02 00:06:00+00,2015-02-02 00:13:00+00,496,E 16 St & 5 Ave,40.737262,-73.992390,237,E 11 St & 2 Ave,40.730473,-73.986724,15475,Subscriber,1992.0,2
6,6446,NaN,NaN,304,2015-02-02 00:07:00+00,2015-02-02 00:12:00+00,477,W 41 St & 8 Ave,40.756405,-73.990026,450,W 49 St & 8 Ave,40.762272,-73.987882,16272,Subscriber,1968.0,1
7,6447,NaN,NaN,622,2015-02-02 00:08:00+00,2015-02-02 00:18:00+00,467,Dean St & 4 Ave,40.683125,-73.978951,391,Clark St & Henry St,40.697601,-73.993446,16370,Subscriber,1979.0,1
8,6448,NaN,NaN,371,2015-02-02 00:09:00+00,2015-02-02 00:15:00+00,434,9 Ave & W 18 St,40.743174,-74.003664,482,W 15 St & 7 Ave,40.739355,-73.999318,19437,Subscriber,1963.0,1
9,6449,NaN,NaN,477,2015-02-02 00:11:00+00,2015-02-02 00:19:00+00,330,Reade St & Broadway,40.714505,-74.005628,2008,Little West St & 1 Pl,40.705693,-74.016777,21211,Subscriber,1982.0,1
10,6450,NaN,NaN,743,2015-02-02 00:12:00+00,2015-02-02 00:25:00+00,521,8 Ave & W 31 St,40.750450,-73.994811,423,W 54 St & 9 Ave,40.765849,-73.986905,21417,Subscriber,1978.0,2
11,6451,NaN,NaN,599,2015-02-02 00:12:00+00,2015-02-02 00:22:00+00,504,1 Ave & E 15 St,40.732219,-73.981656,453,W 22 St & 8 Ave,40.744751,-73.999154,15722,Subscriber,1956.0,1
12,6452,NaN,NaN,345,2015-02-02 00:12:00+00,2015-02-02 00:18:00+00,285,Broadway & E 14 St,40.734546,-73.990741,236,St Marks Pl & 2 Ave,40.728419,-73.987140,18972,Subscriber,1962.0,1
13,6453,NaN,NaN,721,2015-02-02 00:13:00+00,2015-02-02 00:25:00+00,301,E 2 St & Avenue B,40.722174,-73.983688,476,E 31 St & 3 Ave,40.743943,-73.979661,19628,Subscriber,1980.0,1
14,6454,NaN,NaN,182,2015-02-02 00:13:00+00,2015-02-02 00:16:00+00,279,Peck Slip & Front St,40.707873,-74.001670,376,John St & William St,40.708621,-74.007222,15169,Subscriber,1978.0,1
15,6455,NaN,NaN,154,2015-02-02 00:13:00+00,2015-02-02 00:16:00+00,342,Columbia St & Rivington St,40.717400,-73.980166,411,E 6 St & Avenue D,40.722281,-73.976687,17533,Subscriber,1997.0,1
16,6456,NaN,NaN,435,2015-02-02 00:14:00+00,2015-02-02 00:21:00+00,470,W 20 St & 8 Ave,40.743453,-74.000040,491,E 24 St & Park Ave S,40.740964,-73.986022,19761,Subscriber,1983.0,1
17,6457,NaN,NaN,310,2015-02-02 00:15:00+00,2015-02-02 00:20:00+00,236,St Marks Pl & 2 Ave,40.728419,-73.987140,393,E 5 St & Avenue C,40.722992,-73.979955,17267,Subscriber,1993.0,1
18,6458,NaN,NaN,1274,2015-02-02 00:16:00+00,2015-02-02 00:37:00+00,470,W 20 St & 8 Ave,40.743453,-74.000040,470,W 20 St & 8 Ave,40.743453,-74.000040,18691,Subscriber,1964.0,1
19,6459,NaN,NaN,642,2015-02-02 00:18:00+00,2015-02-02 00:29:00+00,485,W 37 St & 5 Ave,40.750380,-73.983390,174,E 25 St & 1 Ave,40.738177,-73.977387,17106,Subscriber,1977.0,1
20,6460,NaN,NaN,256,2015-02-02 00:18:00+00,2015-02-02 00:22:00+00,345,W 13 St & 6 Ave,40.736494,-73.997044,483,E 12 St & 3 Ave,40.732233,-73.988900,20009,Subscriber,1973.0,1
21,6461,NaN,NaN,334,2015-02-02 00:19:00+00,2015-02-02 00:25:00+00,489,10 Ave & W 28 St,40.750664,-74.001768,442,W 27 St & 7 Ave,40.746647,-73.993915,18777,Subscriber,1979.0,1
22,6462,NaN,NaN,90,2015-02-02 00:19:00+00,2015-02-02 00:20:00+00,507,E 25 St & 2 Ave,40.739126,-73.979738,174,E 25 St & 1 Ave,40.738177,-73.977387,15357,Subscriber,1989.0,1
23,6463,NaN,NaN,203,2015-02-02 00:20:00+00,2015-02-02 00:23:00+00,380,W 4 St & 7 Ave S,40.734011,-74.002939,405,Washington St & Gansevoort St,40.739323,-74.008119,18487,Subscriber,1983.0,1
24,6464,NaN,NaN,649,2015-02-02 00:22:00+00,2015-02-02 00:32:00+00,334,W 20 St & 7 Ave,40.742388,-73.997262,439,E 4 St & 2 Ave,40.726281,-73.989780,20863,Subscriber,1981.0,1
25,6465,NaN,NaN,319,2015-02-02 00:23:00+00,2015-02-02 00:29:00+00,508,W 46 St & 11 Ave,40.763414,-73.996674,448,W 37 St & 10 Ave,40.756604,-73.997901,16539,Subscriber,1970.0,1
26,6466,NaN,NaN,154,2015-02-02 00:27:00+00,2015-02-02 00:30:00+00,428,E 3 St & 1 Ave,40.724677,-73.987834,301,E 2 St & Avenue B,40.722174,-73.983688,18737,Subscriber,1961.0,1
27,6467,NaN,NaN,550,2015-02-02 00:28:00+00,2015-02-02 00:37:00+00,331,Pike St & Monroe St,40.711731,-73.991930,195,Liberty St & Broadway,40.709056,-74.010434,17797,Subscriber,1980.0,2
28,6468,NaN,NaN,268,2015-02-02 00:29:00+00,2015-02-02 00:34:00+00,529,W 42 St & 8 Ave,40.757570,-73.990985,478,11 Ave & W 41 St,40.760301,-73.998842,20638,Subscriber,1990.0,1
29,6469,NaN,NaN,153,2015-02-02 00:29:00+00,2015-02-02 00:31:00+00,421,Clermont Ave & Park Ave,40.695734,-73.971297,366,Clinton Ave & Myrtle Ave,40.693261,-73.968896,17636,Subscriber,1989.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32939,39381,NaN,NaN,321,2015-02-06 23:47:00+00,2015-02-06 23:52:00+00,465,Broadway & W 41 St,40.755136,-73.986580,492,W 33 St & 7 Ave,40.750200,-73.990931,18249,Subscriber,1957.0,1
32940,39382,NaN,NaN,449,2015-02-06 23:48:00+00,2015-02-06 23:55:00+00,523,W 38 St & 8 Ave,40.754666,-73.991382,318,E 43 St & Vanderbilt Ave,40.753202,-73.977987,19146,Subscriber,1972.0,2
32941,39383,NaN,NaN,120,2015-02-06 23:48:00+00,2015-02-06 23:50:00+00,509,9 Ave & W 22 St,40.745497,-74.001971,434,9 Ave & W 18 St,40.743174,-74.003664,15313,Subscriber,1984.0,1
32942,39384,NaN,NaN,977,2015-02-06 23:49:00+00,2015-02-07 00:05:00+00,274,Lafayette Ave & Fort Greene Pl,40.686919,-73.976682,2002,Wythe Ave & Metropolitan Ave,40.716887,-73.963198,18469,Subscriber,1979.0,1
32943,39385,NaN,NaN,501,2015-02-06 23:49:00+00,2015-02-06 23:57:00+00,402,Broadway & E 22 St,40.740343,-73.989551,403,E 2 St & 2 Ave,40.725029,-73.990697,18929,Subscriber,1966.0,1
32944,39386,NaN,NaN,441,2015-02-06 23:50:00+00,2015-02-06 23:58:00+00,545,E 23 St & 1 Ave,40.736502,-73.978095,402,Broadway & E 22 St,40.740343,-73.989551,19009,Subscriber,1987.0,1
32945,39387,NaN,NaN,388,2015-02-06 23:50:00+00,2015-02-06 23:57:00+00,325,E 19 St & 3 Ave,40.736245,-73.984738,438,St Marks Pl & 1 Ave,40.727791,-73.985649,17102,Subscriber,1984.0,1
32946,39388,NaN,NaN,607,2015-02-06 23:51:00+00,2015-02-07 00:01:00+00,293,Lafayette St & E 8 St,40.730287,-73.990765,266,Avenue D & E 8 St,40.723684,-73.975748,18686,Subscriber,1972.0,2
32947,39389,NaN,NaN,284,2015-02-06 23:51:00+00,2015-02-06 23:55:00+00,402,Broadway & E 22 St,40.740343,-73.989551,472,E 32 St & Park Ave,40.745712,-73.981948,15377,Subscriber,1989.0,1
32948,39390,NaN,NaN,271,2015-02-06 23:51:00+00,2015-02-06 23:56:00+00,383,Greenwich Ave & Charles St,40.735238,-74.000271,435,W 21 St & 6 Ave,40.741740,-73.994156,17844,Subscriber,1984.0,1
32949,39391,NaN,NaN,572,2015-02-06 23:52:00+00,2015-02-07 00:01:00+00,361,Allen St & Hester St,40.716059,-73.991908,438,St Marks Pl & 1 Ave,40.727791,-73.985649,21040,Subscriber,1987.0,1
32950,39392,NaN,NaN,498,2015-02-06 23:53:00+00,2015-02-07 00:01:00+00,503,E 20 St & Park Ave,40.738274,-73.987520,380,W 4 St & 7 Ave S,40.734011,-74.002939,19480,Subscriber,1981.0,1
32951,39393,NaN,NaN,425,2015-02-06 23:53:00+00,2015-02-07 00:00:00+00,324,DeKalb Ave & Hudson Ave,40.689888,-73.981013,258,DeKalb Ave & Vanderbilt Ave,40.689407,-73.968855,21130,Subscriber,1978.0,1
32952,39394,NaN,NaN,267,2015-02-06 23:53:00+00,2015-02-06 23:58:00+00,496,E 16 St & 5 Ave,40.737262,-73.992390,435,W 21 St & 6 Ave,40.741740,-73.994156,16934,Subscriber,1983.0,1
32953,39395,NaN,NaN,165,2015-02-06 23:53:00+00,2015-02-06 23:56:00+00,484,W 44 St & 5 Ave,40.755003,-73.980144,318,E 43 St & Vanderbilt Ave,40.753202,-73.977987,20745,Subscriber,1968.0,1
32954,39396,NaN,NaN,751,2015-02-06 23:54:00+00,2015-02-07 00:06:00+00,464,E 56 St & 3 Ave,40.759345,-73.967597,507,E 25 St & 2 Ave,40.739126,-73.979738,16811,Subscriber,1969.0,1
32955,39397,NaN,NaN,747,2015-02-06 23:54:00+00,2015-02-07 00:07:00+00,301,E 2 St & Avenue B,40.722174,-73.983688,476,E 31 St & 3 Ave,40.743943,-73.979661,21259,Subscriber,1980.0,1
32956,39398,NaN,NaN,511,2015-02-06 23:54:00+00,2015-02-07 00:03:00+00,439,E 4 St & 2 Ave,40.726281,-73.989780,375,Mercer St & Bleecker St,40.726795,-73.996951,15618,Subscriber,1993.0,1
32957,39399,NaN,NaN,489,2015-02-06 23:54:00+00,2015-02-07 00:02:00+00,497,E 17 St & Broadway,40.737050,-73.990093,486,Broadway & W 29 St,40.746201,-73.988557,17370,Subscriber,1959.0,1
32958,39400,NaN,NaN,1183,2015-02-06 23:55:00+00,2015-02-07 00:14:00+00,504,1 Ave & E 15 St,40.732219,-73.981656,295,Pike St & E Broadway,40.714067,-73.992939,19430,Subscriber,1984.0,1
32959,39401,NaN,NaN,649,2015-02-06 23:55:00+00,2015-02-07 00:06:00+00,510,W 51 St & 6 Ave,40.760660,-73.980420,512,W 29 St & 9 Ave,40.750073,-73.998393,18303,Subscriber,1986.0,1
32960,39402,NaN,NaN,377,2015-02-06 23:55:00+00,2015-02-07 00:01:00+00,254,W 11 St & 6 Ave,40.735324,-73.998004,453,W 22 St & 8 Ave,40.744751,-73.999154,20360,Subscriber,1990.0,1
32961,39403,NaN,NaN,485,2015-02-06 23:56:00+00,2015-02-07 00:04:00+00,470,W 20 St & 8 Ave,40.743453,-74.000040,491,E 24 St & Park Ave S,40.740964,-73.986022,21564,Subscriber,1983.0,1
32962,39404,NaN,NaN,298,2015-02-06 23:56:00+00,2015-02-07 00:01:00+00,482,W 15 St & 7 Ave,40.739355,-73.999318,368,Carmine St & 6 Ave,40.730386,-74.002150,21575,Subscriber,1983.0,1
32963,39405,NaN,NaN,648,2015-02-06 23:57:00+00,2015-02-07 00:07:00+00,461,E 20 St & 2 Ave,40.735877,-73.982050,346,Bank St & Hudson St,40.736529,-74.006180,21014,Subscriber,1983.0,1
32964,39406,NaN,NaN,1261,2015-02-06 23:58:00+00,2015-02-07 00:19:00+00,252,MacDougal St & Washington Sq,40.732264,-73.998522,450,W 49 St & 8 Ave,40.762272,-73.987882,17797,Subscriber,1989.0,2
32965,39407,NaN,NaN,331,2015-02-06 23:58:00+00,2015-02-07 00:04:00+00,324,DeKalb Ave & Hudson Ave,40.689888,-73.981013,270,Adelphi St & Myrtle Ave,40.693083,-73.971789,16975,Subscriber,1984.0,1
32966,39408,NaN,NaN,629,2015-02-06 23:59:00+00,2015-02-07 00:10:00+00,345,W 13 St & 6 Ave,40.736494,-73.997044,236,St Marks Pl & 2 Ave,40.728419,-73.987140,19820,Subscriber,1982.0,1
32967,39409,NaN,NaN,492,2015-02-06 23:59:00+00,2015-02-07 00:07:00+00,263,Elizabeth St & Hester St,40.717290,-73.996375,502,Henry St & Grand St,40.714215,-73.981346,19487,Subscriber,1966.0,1
32968,39410,NaN,NaN,329,2015-02-06 23:59:00+00,2015-02-07 00:04:00+00,401,Allen St & Rivington St,40.720196,-73.989978,301,E 2 St & Avenue B,40.722174,-73.983688,15426,Subscriber,1987.0,1

In [37]:
test = '''
SELECT AVG(tripduration) as avgtrips FROM citibike
WHERE extract(DOW FROM starttime) not in (0,6)
'''

In [38]:
pd.read_csv(io.BytesIO(queryCartoDB(test)), sep=',')

     avgtrips  Unnamed: 1
0  681.052292         NaN

The average trip duration for weekday is 662.94 s

## Task 3
### a. Showing the list of start station locations

In [44]:
test = '''
SELECT CDB_TransformToWebmercator(CDB_LatLng(start_station_latitude, start_station_longitude)) 
             as the_geom_webmercator,
       MIN(cartodb_id) as cartodb_id,
       MIN(start_station_name) as start_station_name 
FROM citibike
GROUP BY start_station_latitude, start_station_longitude
'''

In [45]:
pd.read_csv(io.BytesIO(queryCartoDB(test)), sep=',')

,the_geom_webmercator,cartodb_id,start_station_name
0,0101000020110F0000863F88A4096A5FC19D1DAFD5DFF1...,84,Lafayette Ave & Fort Greene Pl
1,0101000020110F0000BB2EC9F82D6A5FC19150E1B461FB...,412,E 43 St & Vanderbilt Ave
2,0101000020110F0000D62721D3CA6D5FC157A5D529F6F5...,516,Greenwich St & Warren St
3,0101000020110F000060197671C96C5FC197A854AF46FA...,359,9 Ave & W 22 St
4,0101000020110F0000993A68067B6C5FC1B222DA492BFA...,78,W 22 St & 8 Ave
5,0101000020110F00004FF9F3E90D6D5FC1F284479FC8F9...,1019,9 Ave & W 16 St
6,0101000020110F00003816CC930D6B5FC17B393D28A0F9...,110,E 24 St & Park Ave S
7,0101000020110F00006B6C9CBF186A5FC109C57CA0D8FC...,7,W 56 St & 6 Ave
8,0101000020110F00008B8D725EB16B5FC1BF41718A0DF6...,460,Allen St & Hester St
9,0101000020110F0000BA97F1D5D36C5FC13D326BC3E4F5...,799,Centre St & Worth St
10,0101000020110F000052716DFB7B6D5FC1634AEE724BF4...,5444,Old Slip & Front St
11,0101000020110F000079B8DA32AB685FC194DBF126F9F4...,459,Bedford Ave & S 9th St
12,0101000020110F000004115CC3E56B5FC1D8A47A41AFF7...,618,Great Jones St
13,0101000020110F00006C38A18AC36A5FC1CCDA8D8DAFFC...,288,Broadway & W 51 St
14,0101000020110F0000EC774642E56C5FC13DF29213A3F7...,26,MacDougal St & Prince St
15,0101000020110F00006EAC10AF716A5FC1491D46B773FC...,519,W 51 St & 6 Ave
16,0101000020110F0000F211F9C1C7695FC1E298B1F0A7F1...,707,S Portland Ave & Hanson Pl
17,0101000020110F00002FE7B4B3FC6D5FC150F152E3E5F5...,1205,Murray St & West St
18,0101000020110F0000C12D0F658D675FC1323CC0ADCAF2...,6,Willoughby Ave & Walworth St
19,0101000020110F00007392D1EEBD685FC17A448F6F1AF2...,8955,Lafayette Ave & St James Pl
20,0101000020110F00003CBD186C2C6A5FC1C2D62BADBCF6...,370,Avenue D & E 3 St
21,0101000020110F0000B8ECD5128D6D5FC1CF0946E36EF6...,797,Harrison St & Hudson St
22,0101000020110F00007BC267B2266C5FC14EDB28B171F2...,153,Henry St & Atlantic Ave
23,0101000020110F0000C74600C9BE6B5FC1451EF62F18F9...,424,E 16 St & 5 Ave
24,0101000020110F0000F9471F1F9A6C5FC125B4B2DACDF8...,55,Greenwich Ave & Charles St
25,0101000020110F0000B4B6D9A8FF695FC1B42BC0556EF1...,3237,Atlantic Ave & Fort Greene Pl
26,0101000020110F00005293059FE96B5FC1283F96AE66FD...,387,W 52 St & 11 Ave
27,0101000020110F0000F9420761D76C5FC19CAEC2F187F6...,1151,Lispenard St & Broadway
28,0101000020110F00001EF7B62F966B5FC1649B856FF3FA...,252,W 33 St & 7 Ave
29,0101000020110F00002011DE6425685FC115AB984DDAF1...,653,Lexington Ave & Classon Ave
...,...,...,...
297,0101000020110F00003A962D08646B5FC1C2CAB91C36F2...,574,State St & Smith St
298,0101000020110F0000BECCC59977685FC1A94F3336D6F2...,968,Emerson Pl & Myrtle Ave
299,0101000020110F00009492832C826A5FC13DFED2D04CF2...,115,DeKalb Ave & Hudson Ave
300,0101000020110F0000CECBC1AD456B5FC149916BC5DDFD...,1386,W 59 St & 10 Ave
301,0101000020110F00002E55C204246D5FC1CA6FCB5F1FFB...,306,11 Ave & W 27 St
302,0101000020110F00005A738F401D6A5FC1E98304C839F9...,218,E 25 St & 1 Ave
303,0101000020110F00000DCC625D696D5FC158A6C354E2F6...,2184,Laight St & Hudson St
304,0101000020110F0000E9C5F392EA6A5FC14849234B6AF3...,805,Concord St & Bridge St
305,0101000020110F000029CC2D4A18685FC1860D5E9389F1...,410,Monroe St & Classon Ave
306,0101000020110F0000B056ADFF5C6A5FC1500051A8DCF1...,533,3 Ave & Schermerhorn St
307,0101000020110F0000416B223CE96B5FC1EE8BEFEA70FA...,411,W 27 St & 7 Ave
308,0101000020110F000049FA5A0D3A695FC1BA4AA87F7AF1...,2402,Fulton St & Clermont Ave
309,0101000020110F000055982AD3F16B5FC1607FD69C04F6...,339,Forsyth St & Canal St
310,0101000020110F0000A452F7AC7B6B5FC185F5C472A5F6...,83,Allen St & Rivington St
311,0101000020110F000001D7D2EC996C5FC1E4C65FCA5FF8...,216,Washington Pl & 6 Ave
312,0101000020110F00003410F605196D5FC18E052E1DD2F8...,1092,Perry St & Bleecker St
313,0101000020110F00006F4EDEDB7D6A5FC177CDA056BEF6...,81,E 2 St & Avenue C
314,0101000020110F00001288289AB06A5FC143D788E4D9FC...,303,Broadway & W 53 St
315,0101000020110F00000AFD8FC8C36C5FC15AF2587A04FB...,176,10 Ave & W 28 St
316,0101000020110F00001607D538556B5FC119A6CA6F41FC...,124,W 45 St & 8 Ave
317,0101000020110F0000049C1A69CE6C5FC1205139A81BF8...,13,Carmine St & 6 Ave
318,0101000020110F00002FD56A5DDF685FC1A458A08E56F1...,765,Fulton St & Waverly Ave
319,0101000020110F00002D1B19CE146C5FC11E9608E2CDF3...,1737,Columbia Heights & Cranberry St
320,0101000020110F0000E463F723266A5FC14F49CEE530FB...,2481,Pershing Square North
321,0101000020110F00005E9509B1416B5FC19122492B05FD...,71,W 52 St & 9 Ave
322,0101000020110F000020CE41FA366A5FC1E47EC45CABFA...,491,E 37 St & Lexington Ave
323,0101000020110F000084B804B2CF6A5FC14B886A9682F7...,128,E 7 St & Avenue A
324,0101000020110F0000D13ED956106D5FC18EB95BEE7AFA...,239,W 22 St & 10 Ave
325,0101000020110F00003F37CE288B6C5FC17049FA687DF6...,971,Howard St & Centre St
326,0101000020110F000035628033456B5FC1909E3C7438F6...,1146,Norfolk St & Broome St

### b. Showing the numbers of trips started per station but only for stations within 500m of Time Square

In [46]:
test = '''
SELECT CDB_TransformToWebmercator(
                CDB_LatLng(start_station_latitude, 
                           start_station_longitude)
       ) as the_geom_webmercator, 
       MIN(cartodb_id) as cartodb_id,
       COUNT(tripduration) as numtrips,
       MIN(start_station_name) as start_station_name
FROM citibike
WHERE ST_DWithin(
        CDB_LatLng(start_station_latitude,
                   start_station_longitude)::geography,
        CDB_LatLng(40.7577, -73.9857)::geography,
      500)
GROUP BY start_station_latitude, start_station_longitude
'''

In [47]:
pd.read_csv(io.BytesIO(queryCartoDB(test)), sep=',')

,the_geom_webmercator,cartodb_id,numtrips,start_station_name
0,0101000020110F0000F22A632FBE6A5FC1363A28CFADFB...,1115,112,W 43 St & 6 Ave
1,0101000020110F000004AF971C1D6B5FC17A48F3C1A8FB...,54,251,Broadway & W 41 St
2,0101000020110F00001607D538556B5FC119A6CA6F41FC...,124,141,W 45 St & 8 Ave
3,0101000020110F00003F9300B2976B5FC1B8B88F3102FC...,783,221,W 42 St & 8 Ave
4,0101000020110F0000F55695027D6B5FC186E5BB69D7FB...,33,507,W 41 St & 8 Ave
5,0101000020110F000020D6742CE16A5FC112F4D73D73FC...,42,213,Broadway & W 49 St
6,0101000020110F00009BB87D02B76A5FC146C144E9E5FB...,19,141,W 45 St & 6 Ave

## Task 4   
## Find the station that had the longest average trip duration during weekends and within 500m of TimeSquare!

In [48]:
test = '''
SELECT CDB_TransformToWebmercator(
                CDB_LatLng(start_station_latitude, 
                           start_station_longitude)
       ) as the_geom_webmercator, 
       MIN(cartodb_id) as cartodb_id,
       COUNT(tripduration) as numtrips,
       AVG(tripduration) as avgtrips,
       MIN(start_station_name) as start_station_name
FROM citibike
WHERE ST_DWithin(
        CDB_LatLng(start_station_latitude,
                   start_station_longitude)::geography,
        CDB_LatLng(40.7577, -73.9857)::geography,
      500) and extract(DOW FROM starttime) in (0,6)
GROUP BY start_station_latitude, start_station_longitude
ORDER BY avgtrips DESC
'''

In [49]:
pd.read_csv(io.BytesIO(queryCartoDB(test)), sep=',')

,the_geom_webmercator,cartodb_id,numtrips,avgtrips,start_station_name
0,0101000020110F000020D6742CE16A5FC112F4D73D73FC...,42,48,1010.104167,Broadway & W 49 St
1,0101000020110F00001607D538556B5FC119A6CA6F41FC...,124,44,762.931818,W 45 St & 8 Ave
2,0101000020110F000004AF971C1D6B5FC17A48F3C1A8FB...,54,33,683.121212,Broadway & W 41 St
3,0101000020110F00009BB87D02B76A5FC146C144E9E5FB...,19,15,675.400000,W 45 St & 6 Ave
4,0101000020110F0000F55695027D6B5FC186E5BB69D7FB...,33,73,643.260274,W 41 St & 8 Ave
5,0101000020110F0000F22A632FBE6A5FC1363A28CFADFB...,1115,10,629.700000,W 43 St & 6 Ave
6,0101000020110F00003F9300B2976B5FC1B8B88F3102FC...,783,28,579.142857,W 42 St & 8 Ave

So the station that had the longest average trip duration during weekends and within 500m of TimeSquare is Broadway & W 49 St.

## Extra for SQL
##     Create lines for trips started from stations within 500m of Times Squares and lasted less than 2 hours. 
## The number of trips per each pair of stations are output as attributes of these lines.

In [50]:
test = '''
SELECT ST_MakeLine(CDB_TransformToWebmercator(CDB_LatLng(start_station_latitude,start_station_longitude)),
             CDB_TransformToWebmercator(CDB_LatLng(end_station_latitude,end_station_longitude)))
                   as the_geom_webmercator,
     MIN(cartodb_id) as cartodb_id,
     COUNT(tripduration) as numtrips,
     MIN(start_station_name) as start_station_name,
     MIN(end_station_name) as end_station_name
FROM citibike
WHERE ST_DWithin(
      CDB_LatLng(start_station_latitude,
            start_station_longitude)::geography,
      CDB_LatLng(40.7577,-73.9857)::geography,
    500)
    AND tripduration<7200
GROUP BY start_station_latitude, start_station_longitude, end_station_latitude, end_station_longitude
'''

In [51]:
pd.read_csv(io.BytesIO(queryCartoDB(test)), sep=',')

,the_geom_webmercator,cartodb_id,numtrips,start_station_name,end_station_name
0,0102000020110F000002000000F22A632FBE6A5FC1363A...,12043,1,W 43 St & 6 Ave,E 25 St & 2 Ave
1,0102000020110F0000020000009BB87D02B76A5FC146C1...,34407,1,W 45 St & 6 Ave,E 31 St & 3 Ave
2,0102000020110F00000200000004AF971C1D6B5FC17A48...,30188,1,Broadway & W 41 St,10 Ave & W 28 St
3,0102000020110F0000020000003F9300B2976B5FC1B8B8...,7566,5,W 42 St & 8 Ave,W 42 St & 8 Ave
4,0102000020110F00000200000020D6742CE16A5FC112F4...,8850,4,Broadway & W 49 St,W 22 St & 10 Ave
5,0102000020110F0000020000003F9300B2976B5FC1B8B8...,31004,1,W 42 St & 8 Ave,E 27 St & 1 Ave
6,0102000020110F00000200000020D6742CE16A5FC112F4...,4636,2,Broadway & W 49 St,W 20 St & 8 Ave
7,0102000020110F000002000000F55695027D6B5FC186E5...,6788,6,W 41 St & 8 Ave,E 56 St & Madison Ave
8,0102000020110F000002000000F22A632FBE6A5FC1363A...,20181,2,W 43 St & 6 Ave,W 49 St & 8 Ave
9,0102000020110F0000020000001607D538556B5FC119A6...,26631,1,W 45 St & 8 Ave,E 33 St & 5 Ave
10,0102000020110F000002000000F22A632FBE6A5FC1363A...,36993,1,W 43 St & 6 Ave,8 Ave & W 33 St
11,0102000020110F000002000000F55695027D6B5FC186E5...,11242,1,W 41 St & 8 Ave,W 11 St & 6 Ave
12,0102000020110F0000020000003F9300B2976B5FC1B8B8...,22083,3,W 42 St & 8 Ave,E 53 St & Lexington Ave
13,0102000020110F0000020000003F9300B2976B5FC1B8B8...,13700,2,W 42 St & 8 Ave,E 33 St & 5 Ave
14,0102000020110F000002000000F55695027D6B5FC186E5...,8798,1,W 41 St & 8 Ave,Broadway & W 55 St
15,0102000020110F0000020000003F9300B2976B5FC1B8B8...,14842,1,W 42 St & 8 Ave,E 47 St & 1 Ave
16,0102000020110F00000200000004AF971C1D6B5FC17A48...,38207,2,Broadway & W 41 St,E 30 St & Park Ave S
17,0102000020110F0000020000009BB87D02B76A5FC146C1...,14181,2,W 45 St & 6 Ave,E 51 St & 1 Ave
18,0102000020110F0000020000001607D538556B5FC119A6...,19813,1,W 45 St & 8 Ave,W 42 St & 8 Ave
19,0102000020110F000002000000F55695027D6B5FC186E5...,36988,1,W 41 St & 8 Ave,E 12 St & 3 Ave
20,0102000020110F0000020000001607D538556B5FC119A6...,43818,1,W 45 St & 8 Ave,W 24 St & 7 Ave
21,0102000020110F000002000000F55695027D6B5FC186E5...,876,3,W 41 St & 8 Ave,W 37 St & 5 Ave
22,0102000020110F000002000000F55695027D6B5FC186E5...,15276,2,W 41 St & 8 Ave,E 16 St & 5 Ave
23,0102000020110F0000020000009BB87D02B76A5FC146C1...,18472,2,W 45 St & 6 Ave,W 13 St & 7 Ave
24,0102000020110F000002000000F22A632FBE6A5FC1363A...,1115,2,W 43 St & 6 Ave,W 56 St & 6 Ave
25,0102000020110F0000020000009BB87D02B76A5FC146C1...,14749,3,W 45 St & 6 Ave,E 55 St & Lexington Ave
26,0102000020110F000002000000F55695027D6B5FC186E5...,26955,2,W 41 St & 8 Ave,9 Ave & W 45 St
27,0102000020110F00000200000020D6742CE16A5FC112F4...,21504,1,Broadway & W 49 St,8 Ave & W 31 St
28,0102000020110F00000200000004AF971C1D6B5FC17A48...,21258,2,Broadway & W 41 St,Broadway & W 32 St
29,0102000020110F00000200000020D6742CE16A5FC112F4...,45898,1,Broadway & W 49 St,E 37 St & Lexington Ave
...,...,...,...,...,...
542,0102000020110F0000020000001607D538556B5FC119A6...,15912,3,W 45 St & 8 Ave,W 33 St & 7 Ave
543,0102000020110F00000200000020D6742CE16A5FC112F4...,9169,7,Broadway & W 49 St,W 44 St & 5 Ave
544,0102000020110F000002000000F55695027D6B5FC186E5...,6319,13,W 41 St & 8 Ave,11 Ave & W 41 St
545,0102000020110F00000200000020D6742CE16A5FC112F4...,570,7,Broadway & W 49 St,E 48 St & 3 Ave
546,0102000020110F0000020000009BB87D02B76A5FC146C1...,13614,3,W 45 St & 6 Ave,W 27 St & 7 Ave
547,0102000020110F0000020000009BB87D02B76A5FC146C1...,20724,1,W 45 St & 6 Ave,W 54 St & 9 Ave
548,0102000020110F000002000000F55695027D6B5FC186E5...,12873,3,W 41 St & 8 Ave,11 Ave & W 59 St
549,0102000020110F000002000000F55695027D6B5FC186E5...,13148,5,W 41 St & 8 Ave,E 24 St & Park Ave S
550,0102000020110F00000200000020D6742CE16A5FC112F4...,29300,2,Broadway & W 49 St,W 41 St & 8 Ave
551,0102000020110F00000200000004AF971C1D6B5FC17A48...,19451,5,Broadway & W 41 St,9 Ave & W 22 St
552,0102000020110F000002000000F22A632FBE6A5FC1363A...,37508,1,W 43 St & 6 Ave,W 46 St & 11 Ave
553,0102000020110F0000020000003F9300B2976B5FC1B8B8...,12273,1,W 42 St & 8 Ave,W 33 St & 7 Ave
554,0102000020110F00000200000004AF971C1D6B5FC17A48...,11481,2,Broadway & W 41 St,University Pl & E 14 St
555,0102000020110F00000200000004AF971C1D6B5FC17A48...,11191,1,Broadway & W 41 St,W 20 St & 11 Ave
556,0102000020110F000002000000F22A632FBE6A5FC1363A...,11880,2,W 43 St & 6 Ave,W 56 St & 10 Ave
557,0102000020110F00000200000004AF971C1D6B5FC17A48...,1080,7,Broadway & W 41 St,W 43 St & 10 Ave
558,0102000020110F00000200000004AF971C1D6B5FC17A48...,12908,2,Broadway & W 41 St,8 Ave & W 52 St
559,0102000020110F000002000000F55695027D6B5FC186E5...,31209,1,W 41 St & 8 Ave,9 Ave & W 14 St
560,0102000020110F000002000000F55695027D6B5FC186E5...,285,4,W 41 St & 8 Ave,Broadway & W 24 St
561,0102000020110F0000020000003F9300B2976B5FC1B8B8...,6728,4,W 42 St & 8 Ave,12 Ave & W 40 St
562,0102000020110F0000020000003F9300B2976B5FC1B8B8...,9859,3,W 42 St & 8 Ave,Broadway & W 58 St
563,0102000020110F0000020000009BB87D02B76A5FC146C1...,22366,2,W 45 St & 6 Ave,W 47 St & 10 Ave
564,0102000020110F000002000000F55695027D6B5FC186E5...,43644,1,W 41 St & 8 Ave,Clinton St & Joralemon St
565,0102000020110F000002000000F22A632FBE6A5FC1363A...,35497,2,W 43 St & 6 Ave,W 39 St & 9 Ave
566,0102000020110F00000200000004AF971C1D6B5FC17A48...,22653,1,Broadway & W 41 St,E 16 St & Irving Pl
567,0102000020110F0000020000009BB87D02B76A5FC146C1...,17589,1,W 45 St & 6 Ave,W 45 St & 6 Ave
568,0102000020110F000002000000F55695027D6B5FC186E5...,6472,5,W 41 St & 8 Ave,9 Ave & W 16 St
569,0102000020110F0000020000001607D538556B5FC119A6...,15383,2,W 45 St & 8 Ave,12 Ave & W 40 St
570,0102000020110F0000020000001607D538556B5FC119A6...,13612,3,W 45 St & 8 Ave,Broadway & W 58 St
571,0102000020110F00000200000020D6742CE16A5FC112F4...,13311,9,Broadway & W 49 St,E 47 St & Park Ave

# extra credit: make the function python 2 and 3 compatible so that it works on the  PUI2016_Python3 kernel

##### I've made the function python 2 and 3 compatible.